////
Copyright (c) 2020 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[introduction]]
= Introduction

A Digital Twin System forms the basis for comprehensive digitization of production and logistics by
gradually creating consistent data homogeneity and interoperability.

Any asset -- it can be an actual physical asset like a drilling machine but also something virtual
like a web service -- has a digital representation with consistent semantics, called a _Digital
Twin_. Digital Twins represent those assets and services and provide a shell for their _Aspects_
which define the functionality the Digital Twin supports. Aspects provide the actual data of the
Digital Twin that clients can use. Think of an Aspect as a live thing, i.e., a service that can be
queried to retrieve current or aggregated data. The data can be anything from a single numeric value
-- e.g., a temperature sensor -- to a complex block of data.

Each Aspect references a concrete _Aspect Model_. This model describes in a formal, i.e., machine
readable, format, how an Aspect is structured. The model describes for example the used physical
unit and possible value range of the temperature sensor. Note that even in this simple example, a
conventional approach could not satisfyingly answer the question of where this kind of information
would otherwise live -- in the sensor's data sheet that is only a human-readable document? In the
Aspect's API documentation that is also only human-readable? Should the information about the
sensor's physical range be hard-coded in the Aspect and included in each service reply, even though
it never changes? By expressing it in the Aspect model, the Aspect's semantics can be made available
to consumers of the data in a way that opens up new possibilities.

Therefore, an Aspect model contains both information about runtime data structure (e.g., that there
is a property in the data called "temperature", and that it has a numeric value) and information
that is not part of the runtime data (e.g., the unit or range). It does not, however, contain actual
runtime data (e.g., a numeric value representing the current temperature), as this will be delivered
by an Aspect conforming to this Aspect model. The combination of raw runtime data and its
corresponding Aspect model yields _information_.

To specify an Aspect Model, the _{meta-model-full-name}_ ({meta-model-abbr}) is used. This document
specifies the {meta-model-full-name}.

The Meta Model is specified using the Resource Description Format (RDF,
xref:bamm-specification:appendix:bibliography.adoc#rdf11[[rdf11\]]) and the Terse RDF Triple Language
syntax (TTL, xref:bamm-specification:appendix:bibliography.adoc#turtle[[turtle\]]), together with
validation rules in the Shapes Constraint Language (SHACL,
xref:bamm-specification:appendix:bibliography.adoc#shacl[[shacl\]]). Aspect models are likewise
specified in RDF/Turtle, following {meta-model-abbr} semantics.
