////
Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[localization]]
= Localization of Aspect Models

To understand the possibilities for localization of the models and their implications it is important to understand the differences
between the data types `xsd:string` and `rdf:langString` and/or their respective characteristic
counterparts `bamm-c:Text` and `bamm-c:MultiLanguageText`.

To illustrate the differences between them and to give a typical example for localizable string
that also needs to be included in the runtime payload, consider this model with a scalar `text` property:

[source,turtle,subs="attributes+"]
----
include::example$localization-samples.ttl[tags=simple-text]
----

The JSON payload for this model would then look like this:

[source,json]
----
{
  "text" : "eOMtThyhVNLWUZNRcBaQKxI"
}
----

Notice how the text is just a raw string, without any information about the language it is written in.
When instead the `text` property is modeled as `bamm-c:MultiLanguageText` (instead of `bamm-c:Text`),
the payload would change to include the information about the language and would look something like this:

[source,json]
----
{
  "text" : {
    "en" : "Example multi language string"
  }
}
----

Another common use case is the use of localized texts strictly for documentation purposes. This means that the multilanguage strings
can only be seen when modeling, they are not contained in the runtime payloads.

To illustrate how this is done, consider xref:modeling-guidelines.adoc#enumeration-with-complex-value[this example]
and imagine we would like the descriptions of the possible enumeration
values to have localized versions for multiple languages.
This goal could be achieved by extending the model to look something like the following example:

[source,turtle,subs="attributes+"]
----
include::example$localization-samples.ttl[tags=enum-example]
----

Note the use of the attribute `notInPayload`, ensuring that the `description`
property will never be included in the runtime payloads. Also note how it is possible to use
the `description` property multiple times with different language tags (`@de`) to achieve the proper localization of the texts
for linguistically diverse audiences.
