////
Copyright (c) 2020 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[meta-model-elements]]
= Meta Model Elements

The {meta-model-full-name} ({meta-model-abbr}) specifies the elements from which an Aspect Model can
be built. The following diagram shows the basic building blocks:

image::aspect-meta-model.svg[width=100%]

* A _Property_ represents a named value.

* An _Abstract Entity_ is a logical encapsulation of a shared concept. It has a number of Properties. An _Abstract Entity_ can extend another _Abstract Entity_.

* An _Entity_ is a logical encapsulation of multiple values. It has a number of Properties. An _Entity_ can extend either another _Entity_ or an _Abstract Entity_.

* A _Characteristic_ describes a Property's meaning in the context of the Aspect with information
  such as its data type, if it is a collection, that a string value is to be interpreted as one of a
  fixed number of valid states or that a numeric value has an associated physical unit.

* A _Constraint_ represents a limitation that is applied to another Characteristic (for example on the
  numeric value range or the maximum length of string).

Characteristics, Constraints and element descriptions, are _not part of the data_ an Aspect sends,
but only exist in its model. A number of commonly used Characteristics and Constraints are
predefined in the scope of the {meta-model-full-name}, see section
xref:characteristics.adoc#characteristics[Characteristics] for more information.

* An _Operation_ represents an action that can be triggered on the Aspect. Depending on the Aspect,
  this can, but does not have to, trigger an action on the asset that is represented by the Digital
  Twin, for example switching a part of a machine on or off.

* An _Event_ is a model element that represents a single occurence where the timing is important.
  Assets can for instance emit events to notify other assets in case of special occurences.

* An _Aspect_ is the root element of each Aspect Model and has a number of Properties, Events, and
  Operations.

* A _Unit_ refers to a physical unit, such as _metre_ or _degree celsius_. A catalog of units are
predefined in the scope of the {meta-model-full-name}, see section xref:units.adoc[Units] for an
in-depth description.

* A _Quantity Kind_ describes the kind a Unit refers to, such as _length_ or _temperature_.

* _xref:characteristics.adoc#quantifiable-characteristic[Quantifiable]_ is the Characteristic that
  makes use of a Unit. Other Characteristics that are derived from Quantifiable have a Unit as well.

NOTE: See the sections
xref:modeling-guidelines#declaring-model-elements#attributes-that-all-model-elements-have[Attributes
that all model elements have] and xref:modeling-guidelines#declaring-model-elements[Declaring model
elements] in section xref:modeling-guidelines#aspects[Aspects] for hints on using the model elements
in an Aspect model.
