// Copyright (c) 2020 Robert Bosch Manufacturing Solutions GmbH, all rights reserved

////
This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
////

:page-partial:

[[transports]]
= Transports

Aspect implementations can be realized using different transport protocols. The remainder of this
section specifies mappings for different protocols.

[[mqtt]]
== MQTT

MQTT is a lightweight, publish-subscribe network protocol. Clients exchange messages via _topics_. A
topic can be understood as a named channel, or a thread in a discussion forum. The single elements
of an Aspect are mapped to topics as follows.

[[topic-structure]]
=== Topic Structure

When communicating via MQTT agents must follow the convention for topics:

 <namespace>/<agent_identifier>/<aspect_name>/<version>/<aspect_element_name>

where

* _namespace_ is identical to the _namespace_ part of the
  xref:namespaces.adoc#aspect-model-element-identifiers-definition[Aspect Model URN]
* _agent_identifier_ is the (within the namespace) unique name or id of the
agent or asset that implements the Aspect
* _aspect_name_ is identical to the `element-name` part of the xref:namespaces.adoc#aspect-model-element-identifiers-definition[Aspect Model URN]
* _version_ is identical to the `version` part of the xref:namespaces.adoc#aspect-model-element-identifiers-definition[Aspect Model URN]
* _aspect_element_name_ is the simple name of respective Property, Operation, or Event, i.e., it is
  identical to the `element-name` part of the respective element's
  xref:namespaces.adoc#aspect-model-element-identifiers-definition[Aspect Model URN]

If the Aspect element is an Operation, two more subtopics are introduced to allow for communication
in both directions:

  .../<aspect_operation_name>/REQ
  .../<aspect_operation_name>/RESP

Operation calls are then sent to the `REQ` topic and the agent replies via the `RESP` topic.

=== MQTT-specific payload

As detailed in section xref:payloads.adoc[Payloads] all payload must be JSON encoded. However,
depending on the kind of the Aspect element, additional information must be sent:

* Property payload directly encodes the Property's value according to its specified datatype
* Events are always encoded as JSON object with the required fields `timestamp` and `parameters`.
* Operations must be able to link requests published to the `REQ`-topic to their response which is
published to `RESP`. For this, requests and responses are JSON objects that must contain the
mandatory field `requestId` with a unique string as value. The response for a given request must
then have the same value for `requestId`. The actual content of an Operation call is transmitted via
the optional field `parameters`, carrying the Operation parameters as object, for the request, and
the optional field `response`, containing the answer to the Operation call.

See table xref:table_payload[JSON Schemata for Payloads] for details.

[[table-payload]]
.JSON Schemata for Payloads
|===
|Aspect element | JSON Schema | Example

| Property | <depends on Property spec> | 42
| Event | {
  "type": "object",
  "properties": {
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "parameters": {
      "type": "object"
    }
  },
  "required": [
    "timestamp"
  ]
} |
{
  "timestamp": "2020-11-09T08:42:04.363188Z",
  "parameters": {
    "parameter_1": 42
  }
}
| Operation request | {
  "type": "object",
  "properties": {
    "requestId": {
      "type": "string"
    },
    "parameters": {
      "type": "object"
    }
  },
  "required": [
    "requestId"
  ]
}| {
  "requestId": "6b66328a-6ea2-4268-9d3c-4cf1e80355e3",
  "params": {
    "a": 1,
    "b": 1
  }
}
| Operation response | {
  "type": "object",
  "properties": {
    "requestId": {
      "type": "string"
    },
    "resp": {}
  },
  "required": [
    "requestId"
  ]
}|  {
  "requestId": "6b66328a-6ea2-4268-9d3c-4cf1e80355e3",
  "resp": 2
}
|===

TIP: To allow late joining participants to update to the current state quickly, it is recommended to
publish Properties as _retained messages_. The MQTT broker will then automatically resend the last
published message to the client.
