////
Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[best-practices]]
= Best Practices
:nok-small: icon:times-circle[role="red",size="1x"]
:ok-small: icon:check-circle[role="green",size="1x"]

The following best practices, while not mandatory, are highly recommended for optimal performance and to mitigate potential issues, especially when working with Aspect Models at scale.

[[naming-elements]]
== Naming Elements

To name model elements such as Aspects, Properties, etc., adhere to the xref:ROOT:modeling-guidelines.adoc#naming-rules[naming rules].

For optimal results, also consider the following best practices.

// TODO Is that just a best practice or isn't that actually already part of the naming rules? Should it go there?
=== Apply camel case to acronyms, too

Be strict about the camel case xref:ROOT:modeling-guidelines.adoc#naming-rules[naming rules]. Also apply it to any acronyms that may be present in your model element names.

|===
|{nok-small} DON'T |{ok-small} DO

|`mainECU` +
`MainECU`
|`mainEcu` +
`MainEcu`
|`plantID` +
`PlantID`
|`plantId` +
`PlantId`
|===

//TODO Verify TIP, rephrase where needed
NOTE: Enforcing a strict camel case naming rule, also for acronyms, mitigates issues with further tools parsing Aspect Models. That way, a capital letter can be trusted to always trigger the start of a new name part.

[[choose-abbreviations-carefully]]
=== Choose abbreviations carefully

Avoid abbreviations that are not sufficiently common. Seemingly obvious abbreviations can be misunderstood in different contexts.

* For example, `temp` could mean "temperature" or "temporary".
* On the other hand, using `min` or `max` for “minimum” and “maximum” is commonly used and therefore acceptable.

This does not only apply for names but also for <<writing-advice-for-descriptions,description texts>>.

[[avoid-redundancies]]
=== Avoid redundancies

Do not add redundant suffixes to your model element names (if not necessary).

* In particular, the name of an Aspect should not end with "Aspect".
* On the other hand, to distinguish between, for example, an Entity and a related Characteristic, it is acceptable to add a corresponding suffix.

Also, do not use redundant prefixes.

* For example, when authoring an Aspect Model for the domain _Foo_, do not name your Properties `fooCount`, `fooId`, `fooXyz`, etc. +
NOTE:: Remember that the full identifier of a Property is the versioned namespace concatenated with the element name, e.g., `urn:samm:foo.myapplication:1.0.0#count`, so the `foo` context is already part of `count`&#8203;'s identifier.

=== Create expressive names

For any model element, make sure the name is meaningful.

==== Add payload names for Properties where necessary

If you think a Property is name expressive but too long for the runtime payload,
consider adding xref:ROOT:modeling-guidelines.adoc#payload-names[a payload name] to the Property's usage instead of renaming the Property.

==== Leave out implementation details or optimization goals

The Aspect Model -- including it's respective name -- should be reasonably expressive.
Do not add alleged premature optimizations that actually belong in the Aspect implementation.
For example, leave performance and implementation details to the Aspect implementation itself.
The separation of concerns allows the model to be more stable, reusable, and maintainable.

=== If certain Characteristics are present

If there is exactly one Property in an Aspect that has one of the following Characteristics and no other Properties, consider the following name advice for the Property itself and for the corresponding Aspect.

|===
|Characteristic held by Property|How to name the Property |How to name the Aspect

|xref:ROOT:characteristics.adoc#collection-characteristic[Collection] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#list-characteristic[List] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#set-characteristic[Set] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#sorted-set-characteristic[Sorted Set] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#time-series-characteristic[Time Series] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *singular* and add a `History` suffix to it.
|===

=== Adjust the `preferredName` for reader-friendliness

The attribute `preferredName` is meant to provide a human-readable name, for example, in a documentation generated from an Aspect Model or in a user interface of an application based on an Aspect Model. Consider it a display name.
// TODO Is "Consider it a display name" too sloppy? Too one-dimensional even? Then remove it.

==== Separate words

Should you copy and paste an element's `name` to use it as the `preferredName`, adapt it accordingly. For example, if the `name` consists of more than one word, written in camelCase, separate it into two words:

* `name`: `machineTemperature`
* `preferredName`: `machine temperature`

//TODO Sure about the "start small"/"start as in dictionary" practice? -- Consider updating SAMM resources then, see, for example, preferredNames over here: https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/blob/main/esmf-semantic-aspect-meta-model/src/main/resources/samm/entity/2.2.0/TimeSeriesEntity.ttl

==== Capitalization: as in dictionary, and no article

In English, capital letters are reserved for proper names. Therefore, your `preferredName` usually begins with a lowercase letter, just as you would find the words in a dictionary. Even if the words form a familiar acronym, such as ECU for engine control unit, the term itself is not a proper name and is therefore written in lower case.

For other languages, for example for German, the same practice applies: put the name as you would encounter it in a dictionary.

Also: an article does not belong to the name, avoid any articles.

//TODO Is there any way of referring to the `preferredName` without constantly using it as an attribute name? Does `preferredName` have a preferred name?
The following tables detail examples for transferring a `name`, e.g., `machineTemperature` or `allowDuplicates`, to an appropriate `preferredName`.

|===
|{nok-small} DON'T |{ok-small} DO

|`Machine Temperature` +
`Machine temperature` +
`the machine temperature` +
`a machine temperature`
|`machine temperature`
|`Allow Duplicates` +
`Allow duplicates` +
|`allow duplicates`
|`Engine Control Unit (ECU)` +
`Engine control unit (ECU)` +
|`engine control unit (ECU)`
|`Plant ID` +
`Plant Id` +
`plant Id`
|`plant ID`
|===

|===
|{nok-small} DON'T |{ok-small} DO

|`maschinentemperatur` +
`Maschinen-Temperatur` +
`die Maschinentemperatur` +
`eine Maschinentemperatur`
|`Maschinentemperatur`
|`Erlaube Duplikate` +
|`erlaube Duplikate`
|===

//TODO Verify tip for correctness
TIP: By using words the same way they would appear in a dictionary, the `preferredName` attribute is flexible to be used in further applications.For example, to use it to complete a sentence or message in a UI, it can be used as-is.If used to appear as a tooltip, standing alone, it can be parsed towards starting with a capital letter (recommended for English, other languages may follow different conventions).


[[describing-elements]]
== Describing Elements

The `description` attribute xref:ROOT:modeling-guidelines.adoc#attributes-that-all-model-elements-have[allows for] human-readable text in a specific language. Such information provides context for anyone concerned with an Aspect Model or any applications based on it. Therefore, it is recommended to keep description texts consistent across all model elements and even across all Aspect Models in a namespace (and even better: across various namespaces).

[[writing-advice-for-descriptions]]
=== Writing advice for descriptions

What you already do for the `name` attribute, also applies for the `description` attribute:

* <<choose-abbreviations-carefully,Choose abbreviations carefully>>
* <<avoid-redundancies,Avoid redundancies>>, do not start with "This Entity/Property/Aspect ..." or "This <preferredName> ..."
// TODO Explicitly add this or is it enough to say "avoid redundancies"?  --> "Do not mention the SAMM Class, like "Characteristic", "Trait" etc. Imagine that it can be used in a completely different modelling language" --- If we say it: need some background to understand the issue here

Also consider:

* Do not use brand names or other proper names in descriptions
* If other Properties are mentioned in the description, refer to them by their `preferredName`

=== Start with a capital letter

Start your description with a capital letter. This has several advantages, for example, it:

* Makes descriptions work in further applications, for example, in graphical user interfaces
* Improves readability when working with Aspect Model turtle files

[source,turtle,subs="attributes+,+quotes"]
----
samm:description "Sentence fragment starting with a capital letter"@en ;
----

=== No article

To avoid redundacy and enforce conciseness, leave out any article.

Think about a description as a sentence fragment that completes one of the following sentence starters.

.For descriptions starting with a noun
[source,text,subs="attributes+,+quotes"]
----
This <model element> is (a/the) ...
----

.For descriptions starting with a verb
[source,text,subs="attributes+,+quotes"]
----
This <model element> ...
----

=== About full stops

If you only have one sentence fragment as a description, do not add a full stop. Why? First, it is not needed in a sentence fragment. Second, it enables the description to be used, for example, as a tooltip in user interfaces. Tooltips do not carry full stops.

However, if you want to add more content to the description field, do put a full stop after your initial sentence fragment to separate it from the rest.

.Only add a full stop to your sentence fragment if it is followed by more text
[source,turtle,subs="attributes+,+quotes"]
----
samm:description "Sentence fragment starting with a capital letter. Then we add more content. All end with a full stop."@en ;
----

=== Long descriptions

Adding more content to the initial sentence fragment of your description is fine.
//TODO Are there length restrictions?


.How a longer description could look like
[source,text,subs="attributes+,+quotes"]
----
Sentence fragment starting with a capital letter.

Then we add more content. All ending with full stops. There is more to say about this. Yet another sentence.

NOTE: We can highlight information with a NOTE.

EXAMPLE: We can also give examples. Even more than one, then you would numerate them like EXAMPLE1 etc.

Or we can use ordered or unordered lists. This can be handy for adding further resources that otherwise would not fit into the see attribute.
Like:
1. A list item
2. Another list item
----

.The above text example in turtle notation
[source,turtle,subs="attributes+,+quotes"]
----
samm:description "Sentence fragment starting with a capital letter.\n\nThen we add more content. All ending with full stops. There is more to say about this. Yet another sentence.\n\nNOTE: We can highlight information with a NOTE.\n\nEXAMPLE: We can also give examples.\n\nOr we can use ordered or unordered lists.\nLike:\n1. A list item\n2. Another list item"@en ;
----

Adding line breaks to the text in the turtle file helps to display the text well in further applications.

//TODO Add pic of example description as displayed in AME?

=== Examples

The following table details examples for description texts that have writing issues, explains the issues and indicates how to improve the texts.

|===
|Example model element |{nok-small} Description text with issues |Explanation of issues |{ok-small} Recommended version for description text

//SOURCE: locations.ttl
|Property `houseNumber`
|##n##umber of a building in a street##.##
a|* Start with a capital letter
* No full stop at the end if not followed by further content
|Number of a building in a street

//SOURCE: plant.ttl
|Property `productFamily`
|[.underline]#The# product family
a|* Avoid starting with an article
* Also, just repeating the name is not a proper description
|Set of products sharing similar features

//SOURCE: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.week_based_material_demand/3.0.0/WeekBasedMaterialDemand.ttl
a|Property `materialDemandId` +
{nbsp} +
Preferred Name: `Material Demand ID`
|[.underline]#The Material Demand ID# uniquely identifies the material demand within the business relationship between a customer and its supplier.
|Avoid redundancies: do not start the description with the `preferredName`.
|Uniquely identifies the material demand within the business relationship between a customer and its supplier

//SOURCE: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.generic.digital_product_passport/5.0.0/DigitalProductPassport.ttl
|Entity `IdentificationEntity`
|[.underline]#Entity# with identification information of the product with part type information, local identifiers, other codes and the data carrier.
|Avoid redundancies: in the `name` as well as in the description. Do not start the description by mentioning the model element type.
|Identification information about the product with part-type information, local identifiers, other codes and the data carrier

//TODO Hm, so which brand do we name here then? ;)
|TBD
|TBD
|Do not use brand names or other proper names in descriptions
|TBD

//TODO Example?
|TBD
|TBD
|If other Properties are mentioned in the description, refer to them by their `preferredName`
|TBD

//SOURCE: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.generic.digital_product_passport/5.0.0/DigitalProductPassport.ttl
|Property `dataType`
|Data type that describes the content of the attributes' children and data. In case "object" is selected in the enumeration, the children field will be used in the [.underline]#AdditionalDataEntity# instead of the "data" property. If it is another type, the content will be specified in "data" as a string.
//TODO only valid for Properties?
|If other Properties are mentioned in the description, refer to them by their `preferredName`
//TODO Really repeat redundancy in name in our solution?
|Describes the content of the attributes' children and data. In case "object" is selected in the enumeration, the children field will be used in the Additional Data Entity Entity instead of the "data" property. If it is another type, the content will be specified in "data" as a string.

|TBD
|TBD
|TBD
|TBD
|===

//TODO Delete before filing PR
== TEMP: REQUIREMENTS FROM GH ISSUE
=== The first line of the description

    depending on language:

    for English always start with small letter
    in German as used in dictionary, for nouns capital letter, for verbs small letter

    Do not start with preferred name "the <...>

    no complete sentence


=== Further content in the description

    If additional information needed for explanation add (numerated) notes

    If additional examples needed for explanation add (numerated) examples with captial letter "EXAMPLE ", if only one example then no number

    If see-Attribute information not sufficient add source information

=== Applies to whole description

    do not use abbreviations in description, only if known very widely

    Do not use brand names or other proper names in descriptions

    if other properties are mentioned in the description use the preferred name, not the display name or name

    Do not mention the SAMM Class, like "Characteristic", "Trait" etc. Imagine that it can be used in a completely different modelling language

=== Hm

    formulate description such that it would be a good tool tip +
--> Then we should start start in upper case and not add a dot. It would look really bad if just the fragment sits there. Or do we trust that implementations would parse it towards capitalization? We communicated that we do so for the preferred name.

    formulate description such that is could be the definition in an IEC/ISO glossary +
--> Hm, why? Do we observe any fails in meeting a formal tone? This rule might confuse users


[[choosing-a-numeric-type]]
== Choosing a Numeric Type

While JSON only distinguishes between _number_ (floating point) and _integer_, the
xref:ROOT:datatypes.adoc#data-types[type hierarchy] for Aspect Models provides many more options. There
is a distinction between the numeric core types (`xsd:integer` and the fixed-point type
`xsd:decimal`) and the limited range numbers that correspond to the numeric types as defined in most
programming languages (`xsd:float` and `xsd:double` as well as the integer types `xsd:int`,
`xsd:short` etc.).

IMPORTANT: As an Aspect Model ideally captures as much of the domain semantics as possible, it
should not limit itself according to implementation-specific restrictions. In particular, limited
range numbers should only be used when the semantics of the numeric range are relevant beyond the
implementation of the Aspect. For example, a Property `temperature` of a sensor could use a limited
range type such as `xsd:int`, when the physical sensor can never provide a value outside of this
range, while a Property such as `numberOfProducedItems` is not logically limited, so it should use
`xsd:integer`.

[[choosing-a-unit]]
== Choosing a Unit

When trying to refer to a physical unit, please see the xref:appendix:unitcatalog.adoc[Unit
Catalog]. When searching for the unit, remember that the unit catalog uses British English, e.g.,
_metre_ instead of _meter_.

TIP: If you're modeling quantities for which both the metric system and the imperial system provide
units, such as meter vs. feet, it is always recommended to use the metric system (preferably SI units
like meter or others like kilometer if more common in the domain) – unless there are specific
reasons to create the model differently. In any case, it is strongly discouraged to add multiple
Properties in the same scope representing the same value but only using different units due to the
inherent complexity.

[[choosing-a-characteristic]]
== Choosing a Characteristic

The following decision tree helps to find the right Characteristic for a Property.

IMPORTANT: A common error is using the `Text` Characteristic for anything resembling a string.
`Text` is intended for values that are meant _only_ for humans, for example, a description of a
device that is entered by a user as free text. Values such as identifiers, hostnames, table names,
license plate numbers etc. should not use the `Text` Characteristic.

If you create Characteristics that are not limited to your modeled domain but are generally useful,
please consider contributing them so that they can be included in the {meta-model-full-name}'s
Characteristic catalog.

image::characteristics-decision-tree.svg[width=100%]

[[choosing-constraints]]
== Choosing Constraints

Constraints are used to precisely specify limiting conditions of Characteristics. It is recommended
to use Constraints thoroughly:

. It makes the intent of the respective Property clear for humans reading the model or documentation
generated from the model.
. It allows tooling to generate code for the Aspect that can take the Constraints into account. Validation code corresponding to the Constraints can be directly inserted, thus reducing manual implementation effort.

The following decision tree helps to find matching Constraints for a Characteristic. Note that
multiple Constraints can be combined.

CAUTION: If and only if the value has a xref:ROOT:datatypes.adoc#data-types[string-like value space] and
does _not_ use UTF-8 as an encoding, use an xref:ROOT:characteristics.adoc#encoding-constraint[Encoding
Constraint] for the Property. This will ensure that consumers of the Aspect will not end up with
broken special characters.

image::constraints-decision-tree.svg[width=100%]

[[reusing-elements]]
== Reusing Elements

It is generally advisable to reuse definitions of existing model elements that describe the desired semantics. This not only ensures efficiency
and maintainability but, more importantly, it explicitly expresses that the model builds upon a set of agreed-upon abstractions.
The reuse of existing model element definitions makes it clear that your model talks about _the same thing_. On the other hand,
introducing another definition of an allegedly already existing concept is equivalent to stating that the deliberately newly created definition
does indeed mean something different. This is particularly useful when model elements are created for terminology that can have many different
meanings in various contexts, such as the term "process".

`xref:ROOT:entities.adoc#entities[Entities]`,
`xref:ROOT:characteristics.adoc#characteristics[Characteristics]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-events[Events]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-constraints[Constraints]`, and
`xref:ROOT:modeling-guidelines.adoc#declaring-properties[Properties]` are fundamental components of an Aspect.
Reusing these elements across different Aspects ensures consistency, reduces redundancy, and simplifies the management and
integration of shared attributes and interactions.
