////
Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[best-practices]]
= Best Practices

The following best practices, while not mandatory, are highly recommended for optimal performance and to mitigate potential issues, especially when working with Aspect Models at scale.

[[naming-elements]]
== Naming Elements

To name model elements such as Aspects, Properties, etc., adhere to the xref:ROOT:modeling-guidelines.adoc#naming-rules[naming rules].

For optimal results, also consider the following best practices.

=== Use abbreviations with care

Avoid abbreviations that are not sufficiently common. Seemingly obvious abbreviations can be misunderstood in different contexts.

* For example, `temp` could mean "temperature" or "temporary".
* On the other hand, using `min` or `max` for “minimum” and “maximum” is commonly used and therefore acceptable.

=== Avoid redundancies

Do not add redundant suffixes to your model element names (if not necessary).

* In particular, the name of an Aspect should not end with "Aspect".
* On the other hand, to distinguish between, for example, an Entity and a related Characteristic, it is acceptable to add a corresponding suffix.

Also, do not use redundant prefixes.

* For example, when authoring an Aspect Model for the domain _Foo_, do not name your Properties `fooCount`, `fooId`, `fooXyz`, etc. +
TIP:: Remember that the full identifier of a Property is the versioned namespace concatenated with the element name, e.g., `urn:samm:foo.myapplication:1.0.0#count`, so the `foo` context is already part of `count`&#8203;'s identifier.

=== Create expressive names

For any model element, make sure the name is meaningful.

==== Add payload names for Properties where necessary

If you think a Property is name expressive but too long for the runtime payload,
consider adding xref:ROOT:modeling-guidelines.adoc#payload-names[a payload name] to the Property's usage instead of renaming the Property.

==== Leave out implementation details or optimization goals

The Aspect Model -- including it's respective name -- should be reasonably expressive.
Do not add alleged premature optimizations that actually belong in the Aspect implementation.
For example, leave performance and implementation details to the Aspect implementation itself.
The separation of concerns allows the model to be more stable, reusable, and maintainable.

=== Adjust the `preferredName` for reader-friendliness

The attribute `preferredName` is meant to provide a human-readable name, for example, in a documentation generated from an Aspect Model or in a user interface of an application based on an Aspect Model. Consider it a display name.
// TODO Is "Consider it a display name" too sloppy? Too one-dimensional even? Then remove it.

==== Separate words

Should you copy and paste an element's `name` to use it as the `preferredName`, adapt it accordingly. For example, if the `name` consists of more than one word, written in camelCase, separate it into two words:

* `name`: `machineTemperature`
* `preferredName`: `machine temperature`

//TODO Sure about the "start small"/"start as in dictionary" practice? -- Consider updating SAMM resources then, see, for example, preferredNames over here: https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/blob/main/esmf-semantic-aspect-meta-model/src/main/resources/samm/entity/2.2.0/TimeSeriesEntity.ttl

==== Capitalization: as in dictionary, and no article

In English, capital letters are reserved for proper nouns. Therefore, your `preferredName` typically would to start in lower case, just as you would encounter it in a dictionary.

For other languages, for example for German, the same practice applies: put the name as you would encounter it in a dictionary.

Also: an article does not belong to the name, avoid any articles.

//TODO Is there any way of referring to the `preferredName` without constantly using it as an attribute name? Does `preferredName` have a preferred name?
The following tables detail examples for transferring a `name`, e.g., `machineTemperature` or `allowDuplicates`, to an appropriate `preferredName`.

|===
|DON'T |DO

|`Machine Temperature` +
`Machine temperature` +
`the machine temperature` +
`a machine temperature`
|`machine temperature`
|`Allow Duplicates` +
`Allow duplicates` +
|`allow duplicates`
|===

|===
|DON'T |DO

|`maschinentemperatur` +
`Maschinen-Temperatur` +
`die Maschinentemperatur` +
`eine Maschinentemperatur`
|`Maschinentemperatur`
|`Erlaube Duplikate` +
|`erlaube Duplikate`
|===

//TODO Verify tip for correctness
TIP: By using words the same way they would appear in a dictionary, the `preferredName` attribute is flexible to be used in further applications. For example, to use it to complete a sentence or message in a UI, it can be used as-is. If used to appear as a tooltip, standing alone, it can be parsed towards starting with a capital letter (recommended for English, other languages may follow different conventions).


=== If certain Characteristics are present

If there is exactly one Property in an Aspect that has one of the following Characteristics and no other Properties, consider the following name advice for the Property itself and for the corresponding Aspect.

|===
|Characteristic held by Property|How to name the Property |How to name the Aspect

|xref:ROOT:characteristics.adoc#collection-characteristic[Collection] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#list-characteristic[List] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#set-characteristic[Set] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#sorted-set-characteristic[Sorted Set] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#time-series-characteristic[Time Series] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *singular* and add a `History` suffix to it.
|===

[[Writing-element-descriptions]]
== Writing Element Descriptions




[[choosing-a-numeric-type]]
== Choosing a Numeric Type

While JSON only distinguishes between _number_ (floating point) and _integer_, the
xref:ROOT:datatypes.adoc#data-types[type hierarchy] for Aspect Models provides many more options. There
is a distinction between the numeric core types (`xsd:integer` and the fixed-point type
`xsd:decimal`) and the limited range numbers that correspond to the numeric types as defined in most
programming languages (`xsd:float` and `xsd:double` as well as the integer types `xsd:int`,
`xsd:short` etc.).

IMPORTANT: As an Aspect Model ideally captures as much of the domain semantics as possible, it
should not limit itself according to implementation-specific restrictions. In particular, limited
range numbers should only be used when the semantics of the numeric range are relevant beyond the
implementation of the Aspect. For example, a Property `temperature` of a sensor could use a limited
range type such as `xsd:int`, when the physical sensor can never provide a value outside of this
range, while a Property such as `numberOfProducedItems` is not logically limited, so it should use
`xsd:integer`.

[[choosing-a-unit]]
== Choosing a Unit

When trying to refer to a physical unit, please see the xref:appendix:unitcatalog.adoc[Unit
Catalog]. When searching for the unit, remember that the unit catalog uses British English, e.g.,
_metre_ instead of _meter_.

TIP: If you're modeling quantities for which both the metric system and the imperial system provide
units, such as meter vs. feet, it is always recommended to use the metric system (preferably SI units
like meter or others like kilometer if more common in the domain) – unless there are specific
reasons to create the model differently. In any case, it is strongly discouraged to add multiple
Properties in the same scope representing the same value but only using different units due to the
inherent complexity.

[[choosing-a-characteristic]]
== Choosing a Characteristic

The following decision tree helps to find the right Characteristic for a Property.

IMPORTANT: A common error is using the `Text` Characteristic for anything resembling a string.
`Text` is intended for values that are meant _only_ for humans, for example, a description of a
device that is entered by a user as free text. Values such as identifiers, hostnames, table names,
license plate numbers etc. should not use the `Text` Characteristic.

If you create Characteristics that are not limited to your modeled domain but are generally useful,
please consider contributing them so that they can be included in the {meta-model-full-name}'s
Characteristic catalog.

image::characteristics-decision-tree.svg[width=100%]

[[choosing-constraints]]
== Choosing Constraints

Constraints are used to precisely specify limiting conditions of Characteristics. It is recommended
to use Constraints thoroughly:

. It makes the intent of the respective Property clear for humans reading the model or documentation
generated from the model.
. It allows tooling to generate code for the Aspect that can take the Constraints into account. Validation code corresponding to the Constraints can be directly inserted, thus reducing manual implementation effort.

The following decision tree helps to find matching Constraints for a Characteristic. Note that
multiple Constraints can be combined.

CAUTION: If and only if the value has a xref:ROOT:datatypes.adoc#data-types[string-like value space] and
does _not_ use UTF-8 as an encoding, use an xref:ROOT:characteristics.adoc#encoding-constraint[Encoding
Constraint] for the Property. This will ensure that consumers of the Aspect will not end up with
broken special characters.

image::constraints-decision-tree.svg[width=100%]

[[reusing-elements]]
== Reusing Elements

It is generally advisable to reuse definitions of existing model elements that describe the desired semantics. This not only ensures efficiency
and maintainability but, more importantly, it explicitly expresses that the model builds upon a set of agreed-upon abstractions.
The reuse of existing model element definitions makes it clear that your model talks about _the same thing_. On the other hand,
introducing another definition of an allegedly already existing concept is equivalent to stating that the deliberately newly created definition
does indeed mean something different. This is particularly useful when model elements are created for terminology that can have many different
meanings in various contexts, such as the term "process".

`xref:ROOT:entities.adoc#entities[Entities]`,
`xref:ROOT:characteristics.adoc#characteristics[Characteristics]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-events[Events]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-constraints[Constraints]`, and
`xref:ROOT:modeling-guidelines.adoc#declaring-properties[Properties]` are fundamental components of an Aspect.
Reusing these elements across different Aspects ensures consistency, reduces redundancy, and simplifies the management and
integration of shared attributes and interactions.
