////
Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[best-practices]]
= Best Practices
:nok-small: icon:times-circle[role="red",size="1x"]
:ok-small: icon:check-circle[role="green",size="1x"]

The following best practices, while not mandatory, are highly recommended for optimal performance and to mitigate potential issues, especially when working with Aspect Models at scale.

[[the-name-attribute]]
== The `name` attribute

The `name` attribute is mandatory for all model elements.

Use camel-case capitalization, as detailed in the xref:ROOT:modeling-guidelines.adoc#naming-rules[naming rules].

For optimal results, consider the following best practices:

* <<camel-case-for-acronyms>>
* <<unmistakable-abbreviations>>
* <<no-redundant-prefix>>
* <<no-redundant-suffix>>
* <<meaningful-names>>
* <<add-payload-names-for-properties>>
* <<if-certain-characteristics-are-present>>

In addition to that, there are also best practices for:

* <<the-preferredname-attribute>>
* <<the-description-attribute>>

[[camel-case-for-acronyms]]
=== Camel case for acronyms

For every part of a `name`, also for acronyms, strictly apply camel-case capitalization as detailed in the  xref:ROOT:modeling-guidelines.adoc#naming-rules[naming rules].

For example:

|===
|{nok-small} DON'T |{ok-small} DO

|`mainECU`
|`mainEcu`
|`plantID`
|`plantId`
|`documentURL`
|`documentUrl`
|===

Create names where each capital letter can be trusted to trigger the start of a new name part.

That way, for example, automated case-conversion will produce meaningful names (e.g., when generating code based on an Aspect Model):

|===
|SAMM `name` |Resulting name in generated code (automated case-conversion)

|{nok-small} `documentURL`
|`DOCUMENT_U_R_L` {nok-small}
|{ok-small} `documentUrl`
|`DOCUMENT_URL` {ok-small}
|===

[[unmistakable-abbreviations]]
=== Unmistakable abbreviations

Avoid abbreviations that are not sufficiently common. Seemingly obvious abbreviations in one context can be misunderstood in different contexts.

For example:

|===
|{nok-small} DON'T |{ok-small} DO

|`temp`
|Abbreviation unclear; not recommended. (Could mean "temperature" or "temporary".)
|Abbreviating “minimum” or “maximum” by `min` or `max` is common enough and therefore acceptable.
|`minTemperature` +
`maxSpeed`
|===

Using unmistakable abbreviations also applies for <<abbreviations-in-descriptions,description texts>>.

[[no-redundant-prefix]]
=== No redundant prefix

Do not duplicate information.

Avoid prefixes that repeat a domain (the namespace) an Aspect Model belongs to.

|===
|{nok-small} DON'T |{ok-small} DO

|`fooCount` +
`fooId` +
`fooXyz` +
etc. +
&nbsp; +
Full identifier of such a Property: +
`urn:samm:foo.myapplication:1.0.0#fooCount`
|`count` +
`id` +
`xyz` +
etc. +
&nbsp; +
Full identifier of such a Property: +
`urn:samm:foo.myapplication:1.0.0#count`
|===

NOTE: The full identifier of a Property is the versioned namespace concatenated with the element name, for example, `urn:samm:foo.myapplication:1.0.0#count`. So the `foo` context (namespace) is already part of `count`&#8203;'s identifier.

[[no-redundant-suffix]]
=== No redundant suffix

Do not duplicate information.

Avoid suffixes that repeat the SAMM model element type such as Aspect, Property, etc.

|===
|{nok-small} DON'T |{ok-small} DO

|`MovementAspect` +
&nbsp; +
Result in TTL file: +
`:MovementAspect a samm:Aspect ;`
|`Movement` +
&nbsp; +
Result in TTL file: +
`:Movement a samm:Aspect ;`
|===

TIP: To distinguish between, for example, an Entity and a related Characteristic, it is acceptable to add a corresponding suffix.

[[meaningful-names]]
=== Meaningful names (reduce technical debt)

Choose meaningful names for your model elements to foster reusability and avoid technical debt.

That means:

* Do not simply mirror Property names from data sources like API responses (e.g., JSON).
** Might be convenient in the short term
** But makes it difficult to understand and reuse the model in the future
* Invest the time upfront to choose descriptive names that reflect the purpose and meaning of each element.

TIP: Meaningful names improve code readability and maintainability, whereas arbitrary names make understanding and modifying the model harder in the long run.

Meaningfulness also applies for the `description` attribute; see <<no-repeat-preferredname>>.

[[add-payload-names-for-properties]]
=== Payload names for Properties

An expressive Property `name` can be long.

If you consider a Property's name too long for the runtime payload, xref:ROOT:modeling-guidelines.adoc#payload-names[add a payload name].

NOTE: Do not rename Properties just for the sake of a short runtime payload.

[[if-certain-characteristics-are-present]]
=== If certain Characteristics are present in a "Collection Aspect"

An Aspect with exactly one Property on root level which holds a Collection Characteristic can be perceived as a "Collection Aspect".
Data sets provided by such an Aspect may be very large.
This also applies for other Characteristics, i.e., the List, Set, Sorted Set, and Time Series Characteristics.

For a "Collection Aspect", consider the following naming advice for the Property itself and for the corresponding Aspect.

|===
|Characteristic held by Property|How to name the Property |How to name the Aspect

|xref:ROOT:characteristics.adoc#collection-characteristic[Collection] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#list-characteristic[List] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#set-characteristic[Set] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#sorted-set-characteristic[Sorted Set] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *plural*.

|xref:ROOT:characteristics.adoc#time-series-characteristic[Time Series] Characteristic
|Name the Property `items`.
|Put the Aspect's name in *singular* and add a `History` suffix to it.
|===

[[the-preferredname-attribute]]
== The `preferredName` attribute

The `preferredName` attribute is available for all model elements.

For more information, refer to xref:ROOT:modeling-guidelines.adoc#attributes-that-all-model-elements-have[Attributes that all model elements have].

For optimal results, consider the following best practices:

* <<precise-and-understandable>>
* <<separate-words>>
* <<no-article>>
* <<capitalization-as-in-dictionary>>

In addition to that, there are also best practices for:

* <<the-name-attribute>>
* <<the-description-attribute>>

[[precise-and-understandable]]
=== Precise and understandable

The `preferredName` attribute is meant to provide a human-readable name.

Choose a Preferred Name that is precise and easy to understand.

[TIP]
====
Future users might encounter the Preferred Name, for example:

* As a user of an Aspect Model--in a documentation generated from the Aspect Model
* As a user of a software solution--in a user interface of an application that was built based on the Aspect Model
====


[[separate-words]]
=== Separate words

Should you copy and paste an element's `name` to use it as the `preferredName`, adapt it accordingly.

For example, if the `name` consists of more than one word, written in camel case, separate it into two words:

* `name`: `machineTemperature`
* `preferredName`: `machine temperature`

[[no-article]]
=== No article

While an article and a noun can be combined, they do not automatically form a name.

Therefore, avoid articles in Preferred Names.

|===
|{nok-small} DON'T |{ok-small} DO

|the machine temperature +
a machine temperature
|machine temperature
|===

[[capitalization-as-in-dictionary]]
=== Capitalization: as in dictionary

In English, capital letters are typically reserved for proper names. Therefore, your `preferredName` usually begins with a lowercase letter, just as you would find the words in a dictionary.

Even if the words form a familiar acronym, such as ECU for engine control unit, the term _engine control unit_ itself is not a proper name and is therefore written in lowercase.

[NOTE]
====
By using words the same way they would be listed in a dictionary, the `preferredName` attribute is flexible to be used in further applications. For example:

* To complete an orthographically correct sentence or pop-up message in a user interface, it can be used as-is.
* To appear as a tooltip in a user interface, standing alone, it can be parsed towards capitalization (typically: sentence case, starting the tooltip with a capital letter).
====

*Rationale* Once a Preferred Name is capitalized--in sentence case or title case--it can't be reverted to its dictionary form. This is because the capitalization obscures proper names. To avoid this, input the Preferred Name in lowercase, as it would appear in a dictionary. The only exceptions are proper names, which should be capitalized as they usually would be.

That way, the Preferred Name string can always be parsed towards capitalization (where needed) while still being able to correctly complete sentences in, for example, UI messages.

For example:

|===
|{nok-small} DON'T |{ok-small} DO

|`Machine Temperature` +
`Machine temperature`
|`machine temperature`
|`Allow Duplicates` +
`Allow duplicates` +
|`allow duplicates`
|`Engine Control Unit (ECU)` +
`Engine control unit (ECU)` +
|`engine control unit (ECU)`
|`Plant ID` +
`Plant Id` +
`plant Id`
|`plant ID`
|===

TIP: For other languages, the same practice applies: put the words for the Preferred Name as you would encounter them in a dictionary (except for proper names).

For example, in German:

|===
|{nok-small} DON'T |{ok-small} DO

|`maschinentemperatur` +
`Maschinen-Temperatur` +
`die Maschinentemperatur` +
`eine Maschinentemperatur`
|`Maschinentemperatur`
|`Erlaube Duplikate` +
|`erlaube Duplikate`
|===



[[the-description-attribute]]
== The `description` attribute

The `description` attribute is available for all model elements.

For more information, refer to xref:ROOT:modeling-guidelines.adoc#attributes-that-all-model-elements-have[Attributes that all model elements have].

For optimal results, consider the following best practices:

* <<capitalization-start-uppercase>>
* <<punctuation-end-with-period>>
* <<comprehensible-concise>>
* <<no-repeated-preferredname>>
* <<abbreviations-in-descriptions>>
* <<no-brand-names>>
* <<no-entity-property>>
* <<no-this-preferred-name>>
* <<no-the>>
* <<triple-quotes>>
* <<add-sources>>
* <<markdown-where-needed>>
* <<notes-markdown>>
* <<lists-markdown>>
* <<examples-markdown>>

In addition to that, there are also best practices for:

* <<the-name-attribute>>
* <<the-preferredname-attribute>>

[[capitalization-start-uppercase]]
=== Capitalization: start uppercase

A `description` consists at least of a few words forming a phrase or a sentence fragment.

Start with an uppercase letter.

For example:

|===
|{nok-small} DON'T |{ok-small} DO

|flag indicating whether the asset is currently moving
|Flag indicating whether the asset is currently moving.
|represents a single position in space with optional z coordinate
|Represents a single position in space with optional z coordinate.
|Signifies the Vertical Distance in Reference to a Historic Mean Sea Level as a Vertical Datum
|Signifies the vertical distance in reference to a historic mean sea level as a vertical datum.
|===

[[punctuation-end-with-period]]
=== Punctuation: end with a period

End your `description` with a period (full stop).

Even though it is just a sentence fragment.

|===
|Example model element |{nok-small} DON'T |{ok-small} DO

//SOURCE: locations.ttl
|Property `houseNumber`
|Number of a building in a street##&nbsp;##
|Number of a building in a street.
|===

[[comprehensible-concise]]
=== Writing style: comprehensible, concise

Apply a neutral writing style that is *easy to understand*.
This fosters usability and reusability of an Aspect Model.

Also, be *concise*.
To get an idea, think of definitions in an IEC/ISO glossary.

[[no-repeated-preferredname]]
=== Do not just repeat the `preferredName`

Write a meaningful description.

|===
|Example model element |{nok-small} DON'T |{ok-small} DO

//SOURCE: plant.ttl
|Property `productFamily`
|Product family.
|Set of products sharing similar features.
|===

Regarding meaningfulness, see also the details given for the `name` attribute at <<meaningful-names>>.

[[abbreviations-in-descriptions]]
=== Unmistakable abbreviations

Use abbreviations sparingly.

Only use very common abbreviations; ensure they are not misleading. See also the details provided for the `name` attribute: <<unmistakable-abbreviations>>.

It is acceptable to use editorial abbreviations such as `e.g.` ("for example") or `i.e.` ("that is") or `etc.` ("and so forth").

[[no-brand-names]]
=== No brand names

Where possible, avoid brand, product, or company names in descriptions.

//TODO: Why

[[no-entity-property]]
=== No "Entity", "Property", etc.

SAMM model element terms like Entity, Property, Aspect, etc. do not belong in the `description`.

NOTE: Descriptions must be understandable without knowledge of SAMM.

*Rationale* An Aspect Model may be converted to a different output format or modeling language in which SAMM model elements are unknown. Users unfamiliar with SAMM might find the SAMM terminology confusing.

For example:

|===
|Example model element |{nok-small} DON'T |{ok-small} DO
//SOURCE: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.generic.digital_product_passport/5.0.0/DigitalProductPassport.ttl
|Entity `Identification`
|[.underline]#Entity# with identification information of the product with part type information, local identifiers, other codes and the data carrier.
|Identification information about the product with part-type information, local identifiers, other codes and the data carrier.

|===

TIP: If you need to mention [.underline]#other# Properties etc. in the description, refer to them by their `preferredName`.

[[no-this-preferred-name]]
=== No "This <preferredName> ..."

Do not start the description with "This <preferredName> ..." as this duplicates information.

It might even interfere with further usages of the description, for example, when being displayed in a user interface.

TIP: Start the description as if it was a sentence fragment that would complete a sentence like "This model element is a/the ..." or just "This model element ...".

For example:

|===
|Example model element |{nok-small} DON'T |{ok-small} DO

//SOURCE: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.week_based_material_demand/3.0.0/WeekBasedMaterialDemand.ttl
a|Property `materialDemandId` +
{nbsp} +
Preferred Name: `Material Demand ID`
|[.underline]#The Material Demand ID# uniquely identifies the material demand within the business relationship between a customer and its supplier
|Uniquely identifies the material demand within the business relationship between a customer and its supplier.
|===

[[no-the]]
=== No "The ..."

Avoid starting the `description` with an article (where possible).

|===
|Example model element |{nok-small} DON'T |{ok-small} DO

|Property `altitude`
|[.underline]#The# elevation above sea level zero.
|Elevation above sea level zero.
|===

[[triple-quotes]]
=== Triple quotes in TTL file

For those working with Aspect Models as TTL files, reading descriptions along one long line does not help with grasping a description's meaning. Also long lines hide content far beyond the screen which makes it difficult to skim through TTL files.

Therefore, use the TTL triple quotes operator to mark the description as a section with line breaks.

.Example: Use triple quotes
[source,turtle,subs="attributes+,+quotes"]
----
:TrafficLight a samm-c:Enumeration ;
   samm:preferredName "warning level"@en ;
   ##samm:description """##
      Represents speed of position change.
      Within specification, it turns green.
      Within tolerance, it turns yellow.
      Outside specification, it turns red.
      ##"""@en ;##
   samm:dataType xsd:string ;
   samm-c:values ( "green" "yellow" "red" ) .
----

[[add-sources]]
=== Add sources

To link to resources for further reference, use the xref:ROOT:modeling-guidelines.adoc#attributes-that-all-model-elements-have[the `samm:see` attribute].

In the `description`, mention any sources that you have cited within the description.

.Example: Indicating a definition's source (one line)
[source,turtle,subs="attributes+,+quotes"]
----
samm:description "Information and services representing an entity from a given viewpoint. [SOURCE: IEC 63278-1:2023, editorial changes, no examples]"@en ;
----

.Example: Indicating a definition's source (multiple lines, recommended)
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Information and services representing an entity from a given viewpoint.
   [SOURCE: IEC 63278-1:2023, editorial changes, no examples]
   """@en ;
----

[TIP]
====
To provide the source you have cited, use parentheses and the term SOURCE, followed by a colon.
[source,text,subs="attributes+,+quotes"]
----
[SOURCE: ...]
----
====

Further examples:

.Example description for "service"
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Distinct part of the functionality that is provided by an entity through interfaces.
   [SOURCE: IEC 63278-1:2023; IEC 60050-741:2020, 741-01-28]
   """@en ;
----

.Example description for "system"
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Interacting, interrelated, or interdependent elements forming a complex whole.
   [SOURCE: IEC 63278-1:2023; IEC TS 62443-1-1:2009, 3.2.123]
   """@en ;
----

// TODO await decision

CAUTION: ##Okay to promote sources for citations like that? (= without Markdown)## -- For Markdown versions, these would be options: (copy paste link below)

.Link for tryout (copy & paste to browser)
[source,text]
----
https://spec.commonmark.org/dingus/?text=Information%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0A%5BSOURCE%3A%20%5BIEC%2063278-1%3A2023%5D(http%3A%2F%2Fexample.com)%2C%20editorial%20changes%2C%20no%20examples%5D%0A%0A---%0A%0AInformation%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0A%3E%20%5BSOURCE%3A%20%5BIEC%2063278-1%3A2023%5D(http%3A%2F%2Fexample.com)%2C%20editorial%20changes%2C%20no%20examples%5D%0A%0A---%0A%0A%3E%20Information%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0A%5BSOURCE%3A%20%5BIEC%2063278-1%3A2023%5D(http%3A%2F%2Fexample.com)%2C%20editorial%20changes%2C%20no%20examples%5D%0A%0A---%0A%0A%3E%20Information%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%3E%0A%3E%20%5BSOURCE%3A%20%5BIEC%2063278-1%3A2023%5D(http%3A%2F%2Fexample.com)%2C%20editorial%20changes%2C%20no%20examples%5D%0A%0A---%0A%0AInformation%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0ASource%3A%20%0A~~~%0A%5BIEC%2063278-1%3A2023%5D(http%3A%2F%2Fexample.com)%2C%20editorial%20changes%2C%20no%20examples%0A~~~%0A%0A---%0A%0A~~~%0AInformation%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0A%5BSOURCE%3A%20IEC%2063278-1%3A2023%5D(http%3A%2F%2Fexample.com)%2C%20editorial%20changes%2C%20no%20examples%0A~~~%0A%0A%20%0A
----

[[markdown-where-needed]]
=== Markdown where needed

Where needed, use Markdown (CommonMark https://spec.commonmark.org/0.31.2/[0.31.2]) to:

* Highlight text in blockquotes (such as notes or examples)
* List items in:
** Ordered lists
** Unordered lists

[[notes-markdown]]
=== Notes (Markdown)

.Example: Add a note (Markdown)
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Sentence fragment ending with a period.
   > A note detailing further info.

   More description text.

   > Another note.
   > Note that such notes do not come with determining titles.
   > They don't say "NOTE" or anything.
   """@en ;
----

[[lists-markdown]]
=== Lists (Markdown)

.Example: Use an ordered list (Markdown)
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Some description text that needs an ordered list.
   1. Followed by
   2. That ordered list
   3. Created By
   4. Using numbers and dot delimiters
   5. Conformant to the CommonMark specification
   """@en ;
----

.Example: Use an unordered list (Markdown)
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Some description text that needs an unordered list.
   * Followed by
   * That unordered list (or bullet list)
   * Created By
   * Using asterisks
   * Conformant to the CommonMark specification
   """@en ;
----

[[examples-markdown]]
=== Examples (Markdown)

###TBD###

//TODO await decision

##Option 1--with blockquotes--they can have working URLs##

.Example: Use blockquotes to provide examples
[source,turtle,subs="attributes+,+quotes"]
----
samm:description """
   Information and services representing an entity from a given viewpoint.

   > EXAMPLE 1: examples of information are properties (e.g. maximum temperature), actual parameters (e.g. actual velocity), events (e.g. notification of status change), schematics (electrical), and visualization information (2D and 3D drawings).

   > EXAMPLE 2: examples of services are asset services (for example providing the history of the configuration data or providing the actual velocity) and asset related services (for example providing a simulation).

   > EXAMPLE 3: examples of viewpoints are mechanical, electrical, or commercial characteristics.

   [SOURCE: IEC 63278-1:2023, editorial changes]
   """@en ;
----

https://spec.commonmark.org/dingus/?text=Information%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0A%3E%20EXAMPLE%201%3A%20examples%20of%20information%20are%20properties%20(e.g.%20maximum%20temperature)%2C%20actual%20parameters%20(e.g.%20actual%20velocity)%2C%20events%20(e.g.%20notification%20of%20status%20change)%2C%20schematics%20(electrical)%2C%20and%20visualization%20information%20(2D%20and%203D%20drawings).%0A%0A%3E%20EXAMPLE%202%3A%20examples%20of%20services%20are%20asset%20services%20(for%20example%20providing%20the%20history%20of%20the%20configuration%20data%20or%20providing%20the%20actual%20velocity)%20and%20asset%20related%20services%20(for%20example%20providing%20a%20simulation).%0A%0A%3E%20EXAMPLE%203%3A%20examples%20of%20viewpoints%20are%20mechanical%2C%20electrical%2C%20or%20commercial%20characteristics.%0A%0A%5BSOURCE%3A%20IEC%2063278-1%3A2023%2C%20editorial%20changes%5D[Try it (preview HTML code & example output)]

##Option 2--with fenced code block--they can't contain clickable URLs##

.Example: Use fenced code blocks to provide examples
[source,turtle]
----
samm:description """
   Information and services representing an entity from a given viewpoint.

   ~~~
   EXAMPLE 1: examples of information are properties (e.g. maximum temperature), actual parameters (e.g. actual velocity), events (e.g. notification of status change), schematics (electrical), and visualization information (2D and 3D drawings).
   ~~~

   ~~~
   EXAMPLE 2: examples of services are asset services (for example providing the history of the configuration data or providing the actual velocity) and asset related services (for example providing a simulation).
   ~~~

   ~~~
   EXAMPLE 3: examples of viewpoints are mechanical, electrical, or commercial characteristics.
   ~~~

   [SOURCE: IEC 63278-1:2023, editorial changes]
   """@en ;
----

.Link for tryout (copy & paste to browser)
[source,text]
----
https://spec.commonmark.org/dingus/?text=%20%20%20Information%20and%20services%20representing%20an%20entity%20from%20a%20given%20viewpoint.%0A%0A%20%20%20~~~%0A%20%20%20EXAMPLE%201%3A%20examples%20of%20information%20are%20properties%20(e.g.%20maximum%20temperature)%2C%20actual%20parameters%20(e.g.%20actual%20velocity)%2C%20events%20(e.g.%20notification%20of%20status%20change)%2C%20schematics%20(electrical)%2C%20and%20visualization%20information%20(2D%20and%203D%20drawings).%0A%20%20%20~~~%0A%0A%20%20%20~~~%0A%20%20%20EXAMPLE%202%3A%20examples%20of%20services%20are%20asset%20services%20(for%20example%20providing%20the%20history%20of%20the%20configuration%20data%20or%20providing%20the%20actual%20velocity)%20and%20asset%20related%20services%20(for%20example%20providing%20a%20simulation).%0A%20%20%20~~~%0A%0A%20%20%20~~~%0A%20%20%20EXAMPLE%203%3A%20examples%20of%20viewpoints%20are%20mechanical%2C%20electrical%2C%20or%20commercial%20characteristics.%0A%20%20%20~~~%0A%0A%20%20%20%5BSOURCE%3A%20IEC%2063278-1%3A2023%2C%20editorial%20changes%5D
----


CAUTION: ##Which one?## (Consider: Design decision was for "fenced code block = option 2. But: uses more space in TTL and cannot have working links as clickable URLs are typically not activated for the <code> tag in HTML.--*Still stick to 2/fenced code block?*--Is that even "right", semantically? We won't have actual code examples in Aspect Models, will we?)

////
=== Trash

.Example
[source,turtle,subs="attributes+,+quotes"]
----
samm:description "Sentence fragment ending with a period."@en ;
----


.Elements a long description could include
[source,text]
// [source,text,subs="attributes+,+quotes"]
----
Sentence fragment starting with a capital letter, no article, and ending with a period.

Then, add more content. Use complete sentences and end them with full stops.

NOTE: Highlight information with a NOTE. If you need more than one, numerate them, for example, with NOTE 1, NOTE 2, NOTE 3, etc.

EXAMPLE 1: You can also provide examples. If there is only one example, do not add a number, just use EXAMPLE.

EXAMPLE 2: Another example. Note that every example is separated by line breaks.

EXAMPLE 3: Etc.

You can also use ordered or unordered lists.

An example for an ordered list:

1. A list item, starting the list which is preceded and followed by a line break
2. Another list item
2.1 A sub item
2.1.1 A sub sub item
2.1.2 Another sub sub item
2.2 Another sub item
3. A list item

An example for an unordered list:

* A list item
* Another list item
** A sub item
*** A sub sub item
*** Another sub sub item
** Another sub item
* A list item

To be decided: Asterisk or hyphen to start a list item?

- A list item
- Another list item
-- A sub item
--- A sub sub item
--- Another sub sub item
-- Another sub item
- A list item

Add sources if your definition is taken from another source. For example:

SOURCE: IEC TS 62443-1-1

Or, if you adapted a source's original text:

SOURCE: IEC 63278-1:2023, editorial changes, no examples
----


//TODO To illustrate the last sentence, add a pic of the example description as displayed in AME

////

[[choosing-a-numeric-type]]
== Choosing a Numeric Type

While JSON only distinguishes between _number_ (floating point) and _integer_, the
xref:ROOT:datatypes.adoc#data-types[type hierarchy] for Aspect Models provides many more options. There
is a distinction between the numeric core types (`xsd:integer` and the fixed-point type
`xsd:decimal`) and the limited range numbers that correspond to the numeric types as defined in most
programming languages (`xsd:float` and `xsd:double` as well as the integer types `xsd:int`,
`xsd:short` etc.).

IMPORTANT: As an Aspect Model ideally captures as much of the domain semantics as possible, it
should not limit itself according to implementation-specific restrictions. In particular, limited
range numbers should only be used when the semantics of the numeric range are relevant beyond the
implementation of the Aspect. For example, a Property `temperature` of a sensor could use a limited
range type such as `xsd:int`, when the physical sensor can never provide a value outside of this
range, while a Property such as `numberOfProducedItems` is not logically limited, so it should use
`xsd:integer`.

[[choosing-a-unit]]
== Choosing a Unit

When trying to refer to a physical unit, please see the xref:appendix:unitcatalog.adoc[Unit
Catalog]. When searching for the unit, remember that the unit catalog uses British English, e.g.,
_metre_ instead of _meter_.

TIP: If you're modeling quantities for which both the metric system and the imperial system provide
units, such as meter vs. feet, it is always recommended to use the metric system (preferably SI units
like meter or others like kilometer if more common in the domain) – unless there are specific
reasons to create the model differently. In any case, it is strongly discouraged to add multiple
Properties in the same scope representing the same value but only using different units due to the
inherent complexity.

[[choosing-a-characteristic]]
== Choosing a Characteristic

The following decision tree helps to find the right Characteristic for a Property.

IMPORTANT: A common error is using the `Text` Characteristic for anything resembling a string.
`Text` is intended for values that are meant _only_ for humans, for example, a description of a
device that is entered by a user as free text. Values such as identifiers, hostnames, table names,
license plate numbers etc. should not use the `Text` Characteristic.

If you create Characteristics that are not limited to your modeled domain but are generally useful,
please consider contributing them so that they can be included in the {meta-model-full-name}'s
Characteristic catalog.

image::characteristics-decision-tree.svg[width=100%]

[[choosing-constraints]]
== Choosing Constraints

Constraints are used to precisely specify limiting conditions of Characteristics. It is recommended
to use Constraints thoroughly:

. It makes the intent of the respective Property clear for humans reading the model or documentation
generated from the model.
. It allows tooling to generate code for the Aspect that can take the Constraints into account. Validation code corresponding to the Constraints can be directly inserted, thus reducing manual implementation effort.

The following decision tree helps to find matching Constraints for a Characteristic. Note that
multiple Constraints can be combined.

CAUTION: If and only if the value has a xref:ROOT:datatypes.adoc#data-types[string-like value space] and
does _not_ use UTF-8 as an encoding, use an xref:ROOT:characteristics.adoc#encoding-constraint[Encoding
Constraint] for the Property. This will ensure that consumers of the Aspect will not end up with
broken special characters.

image::constraints-decision-tree.svg[width=100%]

[[reusing-elements]]
== Reusing Elements

It is generally advisable to reuse definitions of existing model elements that describe the desired semantics. This not only ensures efficiency
and maintainability but, more importantly, it explicitly expresses that the model builds upon a set of agreed-upon abstractions.
The reuse of existing model element definitions makes it clear that your model talks about _the same thing_. On the other hand,
introducing another definition of an allegedly already existing concept is equivalent to stating that the deliberately newly created definition
does indeed mean something different. This is particularly useful when model elements are created for terminology that can have many different
meanings in various contexts, such as the term "process".

`xref:ROOT:entities.adoc#entities[Entities]`,
`xref:ROOT:characteristics.adoc#characteristics[Characteristics]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-events[Events]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-constraints[Constraints]`, and
`xref:ROOT:modeling-guidelines.adoc#declaring-properties[Properties]` are fundamental components of an Aspect.
Reusing these elements across different Aspects ensures consistency, reduces redundancy, and simplifies the management and
integration of shared attributes and interactions.
