////
Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[best-practices]]
= Best Practices

[[naming-elements]]
== Naming Elements

In addition to the xref:ROOT:modeling-guidelines.adoc#naming-rules[naming rules], the following points
should be considered when naming elements such as Aspects, Properties or Entities:

* Avoid abbreviations that are not sufficiently common. Seemingly obvious abbreviations can be
  misunderstood in different contexts. For example, "temp" could mean "temperature" or "temporary".
  On the other hand, abbreviating "minimum" and "maximum" with "min" and "max", respectively, is
  fine. The Aspect Model should be reasonably expressive. Do not add alleged premature optimizations
  that belong in the Aspect implementation: if you think a Property is name expressive but too long
  for the runtime payload, consider adding xref:ROOT:modeling-guidelines.adoc#payload-names[a payload
  name] to the Property's usage instead of renaming the Property.

* Do not use redundant naming parts. In particular, the name of an Aspect should not end with
  "Aspect". It is however fine to distinguish between e.g. an Entity and a related Characteristic
  by a suffix when necessary.

* Do not use redundant prefixes, e.g. when authoring an Aspect Model for the domain _Foo_, do not
  name your Properties _fooCount_, _fooId_ etc. Remember that the full identifier of a Property is
  the versioned namespace concatenated with the element name, e.g.
  `urn:samm:{example-ns}.myapplication:1.0.0#count`, so the context is already part of
  `count`&#8203;'s identifier.

* The optional attributes `preferredName` and `description` provide a human-readable name and description, respectively (which will be used by the SDKs for generated documentation, OpenAPI generation, JavaScript code etc). Providing a meaningful `preferredName` and `description` helps users and developers to get more value from the Aspect. Make sure to 
** Make the `preferredName` upper case (since it is often used in titles)
** Separate multiple words by space (unlike the name attribute which is a single word)

* If there is exactly one Property in an Aspect that has a
xref:ROOT:characteristics.adoc#collection-characteristic[Collection],
xref:ROOT:characteristics.adoc#list-characteristic[List],
xref:ROOT:characteristics.adoc#set-characteristic[Set],
xref:ROOT:characteristics.adoc#sorted-set-characteristic[Sorted Set] or
xref:ROOT:characteristics.adoc#time-series-characteristic[Time Series] Characteristic (and no other
Properties), the Property should be named `items`.

* If there is exactly one Property in an Aspect that has a
  xref:ROOT:characteristics.adoc#collection-characteristic[Collection],
  xref:ROOT:characteristics.adoc#list-characteristic[List],
  xref:ROOT:characteristics.adoc#set-characteristic[Set] or
  xref:ROOT:characteristics.adoc#sorted-set-characteristic[Sorted Set] Characteristic (and no other
  Properties), the Aspect's name should be in plural. Otherwise, if there is exactly one Property in
  the Aspect that has a xref:ROOT:characteristics.adoc#time-series-characteristic[Time Series]
  Characteristic, the Aspect's name should end with "History". Otherwise, the Aspect's name should
  be in singular.

[[choosing-a-numeric-type]]
== Choosing a Numeric Type

While JSON only distinguishes between _number_ (floating point) and _integer_, the
xref:ROOT:datatypes.adoc#data-types[type hierarchy] for Aspect Models provides many more options. There
is a distinction between the numeric core types (`xsd:integer` and the fixed-point type
`xsd:decimal`) and the limited range numbers that correspond to the numeric types as defined in most
programming languages (`xsd:float` and `xsd:double` as well as the integer types `xsd:int`,
`xsd:short` etc.).

IMPORTANT: As an Aspect Model ideally captures as much of the domain semantics as possible, it
should not limit itself according to implementation-specific restrictions. In particular, limited
range numbers should only be used when the semantics of the numeric range are relevant beyond the
implementation of the Aspect. For example, a Property `temperature` of a sensor could use a limited
range type such as `xsd:int`, when the physical sensor can never provide a value outside of this
range, while a Property such as `numberOfProducedItems` is not logically limited, so it should use
`xsd:integer`.

[[choosing-a-unit]]
== Choosing a Unit

When trying to refer to a physical unit, please see the xref:appendix:unitcatalog.adoc[Unit
Catalog]. When searching for the unit, remember that the unit catalog uses British English, e.g.,
_metre_ instead of _meter_.

TIP: If you're modeling quantities for which both the metric system and the imperial system provide
units, such as meter vs feet, it is always recommended to use the metric system (preferably SI units
like meter or others like kilometer if more common in the domain) – unless there are specific
reasons to create the model differently. In any case it is strongly discouraged to add multiple
Properties in the same scope representing the same value only using different units due to the
inherent complexity.

[[choosing-a-characteristic]]
== Choosing a Characteristic

The following decision tree helps finding the right Characteristic for a Property.

IMPORTANT: A common error is using the `Text` Characteristic for anything resembling a string.
`Text` is intended for values that are meant _only_ for humans, for example a description of a
device that is entered by a user as free text. Values such as identifiers, hostnames, table names,
license plate numbers etc. should not use the `Text` Characteristic.

If you create Characteristics that are not limited to your modeled domain but are generally useful,
please consider contributing them, so that they can be included in the {meta-model-full-name}'s
Characteristic catalog.

image::characteristics-decision-tree.svg[width=100%]

[[choosing-constraints]]
== Choosing Constraints

Constraints are used to precisely specify limiting conditions of Characteristics. It is recommended
to use Constraints thoroughly:

. It makes the intent of the respective Property clear for humans reading the model or documentation
generated from the model
. It allows tooling to generate code for the Aspect that can take the Constraints into account. Validation code
corresponding to the Constraints can be directly inserted, thus reducing manual implementation effort.

The following decision tree helps finding matching Constraints for a Characteristic. Note that
multiple Constraints can be combined.

CAUTION: If and only if the value has a xref:ROOT:datatypes.adoc#data-types[string-like value space] and
does _not_ use UTF-8 as an encoding, use an xref:ROOT:characteristics.adoc#encoding-constraint[Encoding
Constraint] for the Property. This will ensure that consumers of the Aspect will not end up with
broken special characters.

image::constraints-decision-tree.svg[width=100%]

[[reuse-elements]]
== Reuse Elements

It is generally advisable to reuse definitions of existing model elements that describe the desired semantics. This not only ensures efficiency
and maintainability, but more importantly, it explicitly expresses that the model builds upon a set of agreed-upon abstractions.
Reuse of exising model element definitions makes it clear that your model talks about _the same thing_. On the other hand,
introducing another definition of an allegedly already existing concept is equivalent to stating that the deliberately newly created definition
does indeed mean something different. This is particularly useful when model elements are created for terminology that can have many different
meanings in various contexts, such as the term "process".

`xref:ROOT:entities.adoc#entities[Entities]`, `xref:ROOT:characteristics.adoc#characteristics[Characteristics]`,
`xref:ROOT:modeling-guidelines.adoc#declaring-events[Events]`, `xref:ROOT:modeling-guidelines.adoc#declaring-constraints[Constraints]`
and `xref:ROOT:modeling-guidelines.adoc#declaring-properties[Properties]` are fundamental components of an Aspect.
Reusing these elements across different Aspects ensures consistency, reduces redundancy, and simplifies the management and
integration of shared attributes and interactions.
