////
Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[characteristics]]
= Characteristics and Constraints

[[characteristics-classes]]
== Characteristics Classes

Characteristics Classes describe abstract concepts that must be made specific when they are used.
For example, the Enumeration Characteristic represents the concept "one of multiple predefined
values". In order to use the Characteristic, an instance of it must be specified in the
corresponding Aspect Model, that determines which values are valid for the respective Property.

The following diagram shows the Characteristics Classes defined in the scope of the
{meta-model-full-name}.

image::characteristics-classes.svg[width=100%]

[[characteristic-characteristic]]
=== Characteristic
[.element-urn]
--
{samm-c}Characteristic
--

Base class of all characteristics. This Characteristics Class can also be instantiated directly
(i.e., without creating a subclass).

See xref:modeling-guidelines.adoc#declaring-characteristics[declaring characteristics] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm:preferredName` | Human readable name in a specific language | {nok}
| `samm:description` | Human readable description in a specific language | {nok}
| `samm:dataType` | Reference to a scalar or complex (Entity) data type. See Section "Type System"
  in the Aspect Meta Model | {ok}
|===

[[trait-characteristic]]
=== Trait
[.element-urn]
--
{samm-c}Trait
--

The Trait is used to add one or more <<constraints>> to another Characteristic, which is referred to
as the "base Characteristic".
A Trait itself has no `samm:dataType`, because it inherits the type of its `samm-c:baseCharacteristic`.

See xref:modeling-guidelines.adoc#declaring-constraints[declaring constraints] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:baseCharacteristic` | The Characterstic that is being constrained | {ok}
| `samm-c:constraint` | A Constraint that is applicable to the base Characteristic. This attribute may
  be used multiple times, to add multiple Constraints to the base Characteristic. | {ok}
|===

[[quantifiable-characteristic]]
=== Quantifiable
[.element-urn]
--
{samm-c}Quantifiable
--

A value which can be quantified and may have a unit, e.g., the number of bolts required for a
processing step or the expected torque with which these bolts should be tightened.

See xref:modeling-guidelines.adoc#declaring-characteristics[declaring characteristics] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:unit` | Reference to a Unit as defined in the  xref:units.adoc#units[Unit catalog] | {nok}
|===

[[measurement-characteristic]]
=== Measurement
[.element-urn]
--
{samm-c}Measurement
--

A measurement is a numeric value with an associated unit and quantity kind.

See xref:modeling-guidelines.adoc#declaring-characteristics[declaring characteristics] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:unit` | Reference to a Unit as defined in the xref:units.adoc#units[Unit catalog] | {ok}
|===

[[enumeration-characteristic]]
=== Enumeration
[.element-urn]
--
{samm-c}Enumeration
--

An enumeration represents a list of possible values.

See xref:modeling-guidelines.adoc#declaring-enumerations[declaring enumerations] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:values` | List of possible values. The `dataType` of each of the values must match the
  `dataType` of the Enumeration. | {ok}
|===

[[state-characteristic]]
=== State
[.element-urn]
--
{samm-c}State
--

A state is subclass of Enumeration with a default value.

See xref:modeling-guidelines.adoc#declaring-state[declaring state] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:defaultValue` | The default value for the state | {ok}
|===

[[duration-characteristic]]
=== Duration
[.element-urn]
--
{samm-c}Duration
--

A time duration.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:unit` | Reference to a Unit as defined in the xref:units.adoc#units[Unit catalog]. The
referenced unit or its referenceUnit must have the quantityKind
`xref:appendix:unitcatalog.adoc#quantitykind-time[unit:time]`. Currently, the following units can
therefore be used: `xref:appendix:unitcatalog.adoc#unit-centipoisePerBar[unit:centipoisePerBar]`
`xref:appendix:unitcatalog.adoc#unit-commonYear[unit:commonYear]`
`xref:appendix:unitcatalog.adoc#unit-day[unit:day]`
`xref:appendix:unitcatalog.adoc#unit-henryPerKiloohm[unit:henryPerKiloohm]`
`xref:appendix:unitcatalog.adoc#unit-henryPerOhm[unit:henryPerOhm]`
`xref:appendix:unitcatalog.adoc#unit-hour[unit:hour]`
`xref:appendix:unitcatalog.adoc#unit-kilosecond[unit:kilosecond]`
`xref:appendix:unitcatalog.adoc#unit-microhenryPerKiloohm[unit:microhenryPerKiloohm]`
`xref:appendix:unitcatalog.adoc#unit-microhenryPerOhm[unit:microhenryPerOhm]`
`xref:appendix:unitcatalog.adoc#unit-microsecond[unit:microsecond]`
`xref:appendix:unitcatalog.adoc#unit-millihenryPerKiloohm[unit:millihenryPerKiloohm]`
`xref:appendix:unitcatalog.adoc#unit-millihenryPerOhm[unit:millihenryPerOhm]`
`xref:appendix:unitcatalog.adoc#unit-millipascalSecondPerBar[unit:millipascalSecondPerBar]`
`xref:appendix:unitcatalog.adoc#unit-millisecond[unit:millisecond]`
`xref:appendix:unitcatalog.adoc#unit-minuteUnitOfTime[unit:minuteUnitOfTime]`
`xref:appendix:unitcatalog.adoc#unit-month[unit:month]`
`xref:appendix:unitcatalog.adoc#unit-nanosecond[unit:nanosecond]`
`xref:appendix:unitcatalog.adoc#unit-pascalSecondPerBar[unit:pascalSecondPerBar]`
`xref:appendix:unitcatalog.adoc#unit-picosecond[unit:picosecond]`
`xref:appendix:unitcatalog.adoc#unit-poisePerBar[unit:poisePerBar]`
`xref:appendix:unitcatalog.adoc#unit-poisePerPascal[unit:poisePerPascal]`
`xref:appendix:unitcatalog.adoc#unit-reciprocalMinute[unit:reciprocalMinute]`
`xref:appendix:unitcatalog.adoc#unit-secondUnitOfTime[unit:secondUnitOfTime]`
`xref:appendix:unitcatalog.adoc#unit-shake[unit:shake]`
`xref:appendix:unitcatalog.adoc#unit-siderealYear[unit:siderealYear]`
`xref:appendix:unitcatalog.adoc#unit-tropicalYear[unit:tropicalYear]`
`xref:appendix:unitcatalog.adoc#unit-week[unit:week]`
`xref:appendix:unitcatalog.adoc#unit-year[unit:year]` | {ok}
|===

[[collection-characteristic]]
=== Collection
[.element-urn]
--
{samm-c}Collection
--

A group of values which may be either of a scalar or Entity type. The values may be duplicated and
are not ordered (i.e., bag semantics).

See xref:modeling-guidelines.adoc#declaring-collections[declaring collections] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm:dataType` | Reference to a scalar or complex (Entity) data type. See Section "Type System"
  in the Aspect Meta Model. | {nok}
| `samm-c:elementCharacteristic` | Reference to a Characteristic which describes the individual
  elements contained in the Collection. | {nok}
|===

[[list-characteristic]]
=== List
[.element-urn]
--
{samm-c}List
--

A subclass of <<collection-characteristic>> which may contain duplicates and is ordered.

[[set-characteristic]]
=== Set
[.element-urn]
--
{samm-c}Set
--

A subclass of <<collection-characteristic>> which may not contain duplicates and is unordered.

[[sorted-set-characteristic]]
=== Sorted Set
[.element-urn]
--
{samm-c}SortedSet
--

A subclass of <<collection-characteristic>> which may not contain duplicates and is ordered.

[[time-series-characteristic]]
=== Time Series
[.element-urn]
--
{samm-c}TimeSeries
--

A subclass of <<sorted-set-characteristic>> containing values with the exact point in time when the
values where recorded.

See xref:modeling-guidelines.adoc#declaring-time-series[declaring time series] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm:dataType` | Set to `samm-e:TimeSeriesEntity`. This Entity consists of two Properties, namely
  `samm-e:timestamp` and `samm-e:value`.

As such the structure for time series data is fixed to a collection of key/value pairs with the
timestamp being the key and the value being the value.

The `samm-e:timestamp` property has a fixed Characteristic of `samm-c:Timestamp`. The Characteristic
of the `samm-e:value` Property is set in the specific Aspect Model giving the value domain specific
semantics. | {ok}
|===

[[code-characteristic]]
=== Code
[.element-urn]
--
{samm-c}Code
--

Describes a Property which contains any kind of code. Note that this Characteristic does not define
a `samm:dataType`, this must therefore be done when instantiating the Characteristic.

[[either-characteristic]]
=== Either
[.element-urn]
--
{samm-c}Either
--

Describes a Property whose value can have one of two possible types (a disjoint union).
This Characteristic does not have one explicit `samm:dataType`, as it can be the datatype of either the left or the right.

See xref:modeling-guidelines.adoc#declaring-either[declaring either] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:left` | The left side of the Either. The attribute references another Characteristic which
  describes the value. | {ok}
| `samm-c:right` | The right side of the Either. The attribute references another Characteristic
  which describes the value. | {ok}
|===

[[single-entity-characteristic]]
=== Single Entity
[.element-urn]
--
{samm-c}SingleEntity
--

Describes a Property whose data type is an Entity. The Entity used as data type could be defined in
the same Aspect Model or the shared Entity namespace of the {meta-model-full-name}.

See xref:modeling-guidelines.adoc#declaring-characteristics[declaring characteristics] for usage in an Aspect Model.

[[structured-value-characteristic]]
=== Structured Value
[.element-urn]
--
{samm-c}StructuredValue
--

Describes a Property which contains a scalar xref:datatypes.adoc#data-types[string-like value space]
value with a well-defined structure. The Structured Value Characteristic allows the description of
the parts of the Property's value by linking to a separate Property definition for each part. To
define the parts, the value must be deconstructed using a regular expression.

See xref:modeling-guidelines.adoc#declaring-structured-value[declaring structured value] for usage in an Aspect Model.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:deconstructionRule` | The regular expression used to deconstruct the value into parts that
  are mapped to separate Properties. This regular expression must contain the same number of capture
  groups as there are Properties given in the `elements` list. The _n_&#8203;th capture group maps
  to the _n_&#8203;th Property in the `elements` list. | {ok}
| `samm-c:elements` | A list of entries each of which can either be a Property reference or a string
  literal. The list must contain at least one Property reference. | {ok}
|===

Concatenating the values of the Properties in the `elements` list with the string literals in the
given order should yield a value that corresponds to the original value that has this Structured
Value Characteristic. While the `deconstructionRule` is used for deconstruction, the string literals
in the `elements` list are used for construction. When the Property using the Structured Value
Characteristic also defines an `exampleValue`, construction and deconstruction of the value are
tested when validating the model.

[[characteristics-instances]]
== Characteristics Instances

A number of concrete Characteristics are defined in conjunction with the Aspect Meta Model. They can
be used as-is as Characteristics for Properties in Aspect Models. The following diagram shows the
Characteristics Instances defined in the scope of the {meta-model-full-name}.

image::characteristics-instances.svg[width=100%]

[[timestamp-characteristic]]
=== Timestamp
[.element-urn]
--
{samm-c}Timestamp
--

Describes a Property which contains the date and time with an optional timezone.

dataType: `xref:datatypes.adoc#data-types[xsd:dateTime]`

[[text-characteristic]]
=== Text
[.element-urn]
--
{samm-c}Text
--

Describes a Property which contains plain text. This is intended exclusively for human readable
strings, not for identifiers, measurement values, etc.

dataType: `xref:datatypes.adoc#data-types[xsd:string]`

[[multi-language-text-characteristic]]
=== Multi-Language Text
[.element-urn]
--
{samm-c}MultiLanguageText
--
// From the diagram, readers would aspect to read from left to right, so the MultiLanguageText box should appear to the right of the Text box, as Timestamp box is described first.
Describes a Property which contains plain text in multiple languages. This is intended exclusively
for human readable strings, not for identifiers, measurement values, etc.

dataType: `xref:datatypes.adoc#data-types[rdf:langString]`

[[language-characteristic]]
=== Language
[.element-urn]
--
{samm-c}Language
--

Describes a Property containing a language according to ISO 639-1
xref:samm-specification:appendix:bibliography.adoc#iso639[[iso639\]], for example "de".

dataType: `xref:datatypes.adoc#data-types[xsd:string]`

[[locale-characteristic]]
=== Locale
[.element-urn]
--
{samm-c}Locale
--
Describes a Property containing a locale according to IETF BCP 47
xref:samm-specification:appendix:bibliography.adoc#bcp47[[bcp47\]], for example "de-DE".

dataType: `xref:datatypes.adoc#data-types[xsd:string]`

[[boolean-characteristic]]
=== Boolean
[.element-urn]
--
{samm-c}Boolean
--

Represents a boolean value (i.e., a "flag").

dataType: `xref:datatypes.adoc#data-types[xsd:boolean]`

[[resource-path-characteristic]]
=== Resource Path
[.element-urn]
--
{samm-c}ResourcePath
--

Describes a Property that contains the path to a relative or absolute resource.

dataType: `xref:datatypes.adoc#data-types[xsd:anyURI]`

[[mime-type-characteristic]]
=== MIME Type
[.element-urn]
--
{samm-c}MimeType
--

Describes a Property that contains a MIME type as defined by RFC 2046
xref:samm-specification:appendix:bibliography.adoc#rfc2046[[rfc2046\]], for example "application/json",
"application/xls" or "image/png".

dataType: `xref:datatypes.adoc#data-types[xsd:string]`

[[unit-reference-characteristic]]
=== Unit Reference
[.element-urn]
--
{samm-c}UnitReference
--

Describes a Property containing a reference to one of the units in the
xref:appendix:unitcatalog.adoc#unit-catalog[Unit catalog]. +
See xref:modeling-guidelines.adoc#using-unit-reference[Using Unit Reference] for usage in an Aspect Model.

dataType: `xref:datatypes.adoc#data-types[samm:curie]`

[[constraints]]
== Constraints

[[constraint]]
=== Constraint
[.element-urn]
--
{samm-c}Constraint
--

Base class for other constraints that constrain a Characteristic in some way, e.g., the
<<range-constraint>> limits the value range for a Property.

The Constraint class has no attributes.

[[language-constraint]]
=== Language Constraint
[.element-urn]
--
{samm-c}LanguageConstraint
--

Restricts a value to a specific language.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:languageCode` | An ISO 639-1
  xref:samm-specification:appendix:bibliography.adoc#iso639[[iso639\]] language code for the language of
  the value of the constrained Property, e.g., "de". | {ok}
|===

[[locale-constraint]]
=== Locale Constraint
[.element-urn]
--
{samm-c}LocaleConstraint
--

Restricts a value to a specific locale, i.e., a language with additional region information.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:localeCode` | An IETF BCP 47 xref:samm-specification:appendix:bibliography.adoc#bcp47[[bcp47\]]
  language code for the locale of the value of the constrained Property, e.g., "de-DE". | {ok}
|===

[[range-constraint]]
=== Range Constraint
[.element-urn]
--
{samm-c}RangeConstraint
--
Restricts the value range of a Property. At least one of `samm-c:maxValue` or `samm-c:minValue` must
be present in a Range Constraint. 

Whether the `samm-c:maxValue` and `samm-c:minValue` are inclusive or exclusive can be defined using
the `samm-c:upperBoundDefinition` and `samm-c:lowerBoundDefinition` attributes. 
When one or both of them are not specified, the corresponding value defaults to inclusive.

NOTE: The values for `maxValue` and `minValue` must be given in the same effective dataType that the
constrained Characteristic uses.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:maxValue` | The upper bound of a range | {nok}
| `samm-c:minValue` | The lower bound of a range | {nok}
| `samm-c:upperBoundDefinition` | Defines whether the upper bound of a range is inclusive or
  exclusive. Possible values are `samm-c:AT_MOST` and `samm-c:LESS_THAN` | {nok}
| `samm-c:lowerBoundDefinition` | Defines whether the lower bound of a range is inclusive or
  exclusive. Possible values are `samm-c:AT_LEAST` and `samm-c:GREATER_THAN` | {nok}
|===

NOTE: When either the `samm-c:minValue` or the `samm-c:maxValue` is not given, the Range is defined
as having an open lower or upper boundary.

NOTE: The `AT_LEAST` and `AT_MOST` values for `lowerBoundDefinition` and `upperBoundDefinition`
define that the values for `minValue` and `maxValue` are inclusive. The `LESS_THAN` and
`GREATER_THAN` values for the `lowerBoundDefinition` and `upperBoundDefinition` define that the
values for `minValue` and `maxValue` are exclusive.

This Constraint can be used to restrict Characteristics with one of two kinds of data types:

* Characteristics that have a xref:datatypes.adoc#data-types[numeric data type]; in this case the
Constraint restricts the range of the value. The scalar data types that can be restricted are:
`xsd:double`, `xsd:float`, `xsd:decimal`, `xsd:integer`, `xsd:byte`, `xsd:short`, `xsd:int`,
`xsd:long`, `xsd:unsignedByte`, `xsd:unsignedShort`, `xsd:unsignedInt`, `xsd:unsignedLong`,
`xsd:positiveInteger` , `xsd:nonPositiveInteger`, `xsd:negativeInteger` and
`xsd:nonNegativeInteger`.
* Characteristics that have a xref:datatypes.adoc#data-types[time and date data type]; in this case
the Constraint restricts the scalar data types: `xsd:date`,`xsd:time`, `xsd:dateTime`,
`xsd:dateTimeStamp`, `xsd:gYear`, `xsd:gMonth`, `xsd:gMonthDay`, `xsd:duration`,
`xsd:yearMonthDuration`, `xsd:dayTimeDuration`.

[[encoding-constraint]]
=== Encoding Constraint
[.element-urn]
--
{samm-c}EncodingConstraint
--

Restricts the encoding of a Property.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm:value` | Configures the encoding. This must be one of the following: `samm:US-ASCII`,
  `samm:ISO-8859-1`, `samm:UTF-8`, `samm:UTF-16`, `samm:UTF-16BE` or `samm:UTF-16LE`. | {ok}
|===

NOTE: The default encoding for values with a xref:datatypes.adoc#data-types[string-like value space]
is UTF-8, therefore using an Encoding Constraint with a `samm:value` of `samm:UTF-8` is only
necessary when a Property's encoding is changed during an Aspect Model version increase _from_ some
other encoding _to_ UTF-8 to indicate that the other encoding is not any longer used.

[[length-constraint]]
=== Length Constraint
[.element-urn]
--
{samm-c}LengthConstraint
--

This Constraint can be used to restrict two types of Characteristics:

* Characteristics that have a xref:datatypes.adoc#data-types[string-like value space]; in this case
the Constraint restricts the length of the (string-) value. The scalar data types that can be
restricted are: `xsd:string`, `xsd:date`, `xsd:time`, `xsd:dateTime`, `xsd:dateTimeStamp`,
`xsd:gYear`, `xsd:gMonth`, `xsd:gMonthDay`, `xsd:duration`, `xsd:yearMonthDuration`,
`xsd:dayTimeDuration`, `xsd:hexBinary`, `xsd:base64Binary`, `xsd:anyURI`, `samm:curie` and
`rdf:langString`.
* Collection Characteristics (<<collection-characteristic>>, <<set-characteristic>>,
  <<sorted-set-characteristic>>, <<list-characteristic>>). In this case the Constraint restricts the
  number of elements in the collection.

At least one of `samm-c:maxValue` or `samm-c:minValue` must be present in a Length Constraint.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:maxValue` | The maximum length. Must be given as `xsd:nonNegativeInteger`. | {nok}
| `samm-c:minValue` | The minimum length. Must be given as `xsd:nonNegativeInteger`. | {nok}
|===

[[regular-expression-constraint]]
=== Regular Expression Constraint
[.element-urn]
--
{samm-c}RegularExpressionConstraint
--

Restricts a string value to a regular expression as defined by XQuery 1.0 and XPath 2.0 Functions
and Operators xref:samm-specification:appendix:bibliography.adoc#xpath-functions[[xpath-functions\]].

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm:value` | The regular expression | {ok}
|===

[[fixed-point-constraint]]
=== Fixed Point Constraint
[.element-urn]
--
{samm-c}FixedPointConstraint
--

Defines the scaling factor as well as the amount of integral numbers for a fixed point number. The
constraint may only be used in conjunction with Characteristics which use the `xsd:decimal` data
type.

[width="100%", options="header", cols="30,60,10"]
|===
| Attributes | Description | Required
| `samm-c:scale` | The scaling factor for a fixed point number. E.g., if a fixedpoint number is 123.04, the scaling factor is 2 (the number of digits after the decimal point). Must be given as
  `xsd:positiveInteger`. | {ok}
| `samm-c:integer` | The number of integral digits for a fixed point number. E.g., if a fixedpoint number is 123.04, the integer factor is 3 (the number of digits before the decimal point). Must be given as
  `xsd:positiveInteger`. | {ok}
|===
