////
Copyright (c) 2020 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:

[[mapping-to-json]]
= Mapping to JSON

== Rules for the construction of JSON payloads matching an Aspect Model
image::payloads.svg[opts=interactive, width=100%]

For understanding the construction rules, we define the following terms:

* A Constraint of the Property's Characteristic defined with a Trait is applied to the characteristic referred in the `samm-c:baseCharacteristic` .
* A Property's _effective data type_ means the Property's Characteristic's `samm:dataType`.
* A data type is scalar, if it is one of the xref:datatypes.adoc#data-types[allowed data types], but not a `samm:Entity`.

In order to create JSON payloads that correspond to an Aspect Model, the following rules are
applied. The other way round they can also be used to describe a validation algorithm.

* An Aspect Model is always serialized as an unnamed JSON object.
* For each Property:
** If it is marked as optional, it may or may not be included in the payload. If, and only if, the
   Property is marked as optional and is included in the payload, then its value may be `null`,
   which is equivalent to it not being included in the payload.
** If the Property's effective data type is scalar with any date type other than `rdf:langString`,
   the Property is serialized as `$\{propertyName\}: $\{value\}` where `$\{value\}` is the JSON
   serialization of the respective Property's value, details on mapping of the data types are given
   in <<data-type-mappings>>. The value must adhere to the value range defined by the Property's
   effective data type and possible Constraints on the Property's Characteristic.
** If the Property's effective data type is scalar with the data type `rdf:langString`, the Property
   is serialized as a named JSON object (with `$\{propertyName\}` being the name of the JSON
   property), with keys for each available language tag of the Property and the corresponding
   localized string as the value.
** If the Property's effective data type is not scalar, it is serialized as a named JSON object
   (with `$\{propertyName\}` being the name of the JSON property), recursively using the same rules.
** If the Property's effective data type is an Entity which extends another Entity, it is serialized
   as a named JSON object (with `$\{propertyName\}` being the name of the JSON property). The Properties included for
   the Entity, are the Properties from the Entity itself as well as all Properties from the extended Entities, i.e.
   all Properties from `?thisEntity samm:extends* []`.
** If the Property's Characteristic is a
   xref:characteristics.adoc#collection-characteristic[Collection],
   xref:characteristics.adoc#collection-characteristic[List],
   xref:characteristics.adoc#collection-characteristic[Set] or
   xref:characteristics.adoc#collection-characteristic[Sorted Set], it is serialized as a named JSON
   array (with `$\{propertyName\}` being the name of the JSON array property).
* Characteristics defined in the Aspect Model other than the ones mentioned above are not subject to
  serialization.
* Operations defined in the Aspect Model are not subject to serialization.
* Events defined in the Aspect Model are not subject to serialization.

== Example
=== Aspect Model
[source,turtle,subs="attributes+,+quotes"]
----
@prefix : <urn:samm:{example-ns}.myapplication:1.0.0#> .
@prefix samm: <{samm}> .
@prefix samm-c: <{samm-c}> .
@prefix samm-e: <{samm-e}> .
@prefix unit: <{unit}> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:Movement a samm:Aspect ;
   samm:preferredName "movement"@en ;
   samm:properties ( :isMoving :speed ) ;
   samm:operations ( ) ;
   samm:events ( ) . 

:isMoving a samm:Property ;
   samm:preferredName "is moving"@en ;
   samm:characteristic samm-c:Boolean .

:speed a samm:Property ;
   samm:preferredName "speed"@en ;
   samm:characteristic :Speed ;
   samm:exampleValue "0.5"^^xsd:float .

:Speed a samm-c:Measurement ;
   samm:preferredName "speed"@en ;
   samm:dataType xsd:float ;
   samm-c:unit unit:kilometrePerHour .
----
=== Payload
[source, json]
----
{
  "isMoving": true,
  "speed": 0.5
}
----



[[data-type-mappings]]
== Data type mappings

A xref:datatypes.adoc#data-types[rich type tree] is used in an Aspect Model. As JSON offers only a
very limited set of data types for primitive type values there are less options on how to represent
the data. The mappings are described in the following table.

|===
| | Aspect Model data type | Corresponding JSON data type
.4+| Core Types
| `xsd:string` | String
| `xsd:boolean` | Boolean
| `xsd:decimal` | Number
| `xsd:integer` | Number
.2+| IEEE-floating-point numbers
| `xsd:double` | Number
| `xsd:float` | Number
.4+| Time and date
| `xsd:date` | String
| `xsd:time` | String
| `xsd:dateTime` | String
| `xsd:dateTimeStamp` | String
.8+| Recurring and partial dates
| `xsd:gYear` | String
| `xsd:gMonth` | String
| `xsd:gDay` | String
| `xsd:gYearMonth` | String
| `xsd:gMonthDay` | String
| `xsd:duration` | String
| `xsd:yearMonthDuration` | String
| `xsd:dayTimeDuration` | String
.12+| Limited-range integer numbers
| `xsd:byte` | Number
| `xsd:short` | Number
| `xsd:int` | Number
| `xsd:long` | Number
| `xsd:unsignedByte` | Number
| `xsd:unsignedShort` | Number
| `xsd:unsignedInt` | Number
| `xsd:unsignedLong` | Number
| `xsd:positiveInteger` | Number
| `xsd:nonNegativeInteger` | Number
| `xsd:negativeInteger` | Number
| `xsd:nonPositiveInteger` | Number
.2+| Encoded binary data
| `xsd:hexBinary` | String
| `xsd:base64Binary` | String
.3+| Miscellaneous types
| `xsd:anyURI` | String
| `samm:curie` | String
| `rdf:langString`
| A JSON object with a structure as described in the rules above.
|===

For example, a Property `errorMessage` with effective data type `rdf:langString` and the value
`"Could not load data"@en` would be serialized in the JSON payload as follows:
[source,json]
----
{
  "errorMessage": {
    "en": "Could not load data"    
  }
}
----

A Property `errorMessages` with a Collection Characteristic and effective data type `rdf:langString` could yield the payload:
[source,json]
----
{
  "errorMessages": [
    { "en": "Could not load data" },
    { "de": "Konnte Daten nicht laden" }
  ]
}
----

[[characteristics-payload-mappings]]
== Specific payload mappings for Characteristics

This section describes how data payloads look like for specific xref:characteristics.adoc[Characteristics].

|===
| Characteristic Name | Corresponding JSON data type
| `samm-c:Either` | A JSON object with exactly either a `left` or `right` key. If the `left` key is present, its data type is the effective data type of the Characteristic referred to by `samm-c:left`; if the `right` key is present, its data type is the effective data type of the Characteristic referred to by `samm-c:right`.
|===


The following example Aspect uses `samm-c:Either` to express that the Property `speedValue` can either return the integer value for speed,
or an Error message (using an Entity), if the value could not be determined (cf. xref:modeling-guidelines.adoc#declaring-either[Declaring Either]).

So, assuming an Aspect Model has a Property `speedProperty` with its `samm:characteristic` set to `:Result` according to the following definition:
[source,turtle,subs="attributes+"]
----
include::ROOT:example$either-declaration.ttl[tags=either-declaration]
----

the corresponding JSON payload either contains a `left` key with the error description:
[source,json]
----
{
  "result": {
    "left": {
      "errorCode": "...",
      "errorDescription": "..."
    }
  }
}
----
or it can contain a `right` key with the success status:
[source,json]
----
{
  "result": {
    "right": {
      "status": "..."
    }
  }
}
----

In the following example the Property `speedProperty` can either return the integer value for speed `SpeedValue`,
or an `Error`, if the value could not be determined. `Error` can either return the `samm-c:Text` with simple error text or `ErrorMessage` (using an Entity) for details of error like `errorCode` and `errorDescription`.

So, assuming the Property `speedProperty` with `samm-characteristics` set to `:Result` according to the following definition:
[source,turtle,subs="attributes+"]
----
include::example$aspect-with-double-either-characteristic.ttl[tags=aspect-with-double-either-characteristic]
----

it can contain `right` key with the speed value:
[source,json]
----
{
  "speedProperty": {
    "right": 60
  }
}
----

or possible `left` key of `Error` contains Error message:
[source,json]
----
{
  "speedProperty" : {
    "left" : {
      "right" : {
        "errorDescription" : "...",
        "errorCode" : "..."
      }
    }
  }
}
----

or it can contain `right` key of `Error` with simple error text:
[source,json]
----
{
  "speedProperty" : {
    "left" : {
      "left" : "Simple error description..."
    }
  }
}
----

NOTE: It is necessary to clarify, that sample payload may be invalid.
To be careful when designing Aspect. See an example of a similar case below.

=== Example with Invalid Payload

This example covered situation Sample payload with duplicates in Set and xref:characteristics.adoc#length-constraint[Length Constraint].

----
include::ROOT:example$aspect-property-duplicates-in-set.ttl[tags=aspect-property-duplicates-in-set]
----

=== Payload
[source, json]
----
{
  "property1" : [ false, true, true, false ]
}
----

[[limitations]]
== Limitations

Due to the https://www.ecma-international.org/ecma-262/5.1/#sec-8.5[limits in the
represention of numbers] in JSON, the maximum integer number that can be used without losing
precision is 2⁵³-1 (defined as
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER[Number.MAX_SAFE_INTEGER]).
This means that even if the Aspect Model data type would allow higher or lower values, if they can
not be represented in JSON, they can not be used. Affected data types are the unbounded numeric
types `xsd:decimal`, `xsd:integer`, `xsd:positiveInteger`, `xsd:nonNegativeInteger`,
`xsd:negativeInteger`, `xsd:nonPositiveInteger` and the bounded type `xsd:unsignedLong`. The other
numeric types are not affected.
