////
Copyright (c) 2020 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

:page-partial:
:sectnums:

[[release-notes]]
== Release Notes - {meta-model-full-name}

[[bamm-2.0.0]]
=== Release 2.0.0

- Introduces Entity inheritance. The new *Abstract Entity* Meta Model Element and *extends* attribute may be used to
define a hierarchy of Entities in an Aspect Model. The concept of extending an Entity replaces the existing concept of
refining an Entity.
* The meta model elements `Unit`, `QuantityKinds` and their corresponding attributes were moved from
  the `unit` namespace to the `bamm` namespace. This fixes an inconsistency because the `unit`
  namespace is only intended for the units of the
  xref:bamm-specification:appendix:unitcatalog.adoc#unit-catalog-units[unit catalog].

[[bamm-1.0.0]]
=== Release 1.0.0

This is the initial release for OMP.
