////
Copyright (c) 2020 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

[[site-notice]]
= Site Notice

This is an approved deliverable by the https://open-manufacturing.org[Open Manufacturing Platform (OMP)].

THESE MATERIALS ARE PROVIDED "AS IS."
The parties expressly disclaim any warranties (express, implied, or otherwise), including implied warranties of merchantability, non-infringement, fitness for a particular purpose, or title, related to the materials.
The entire risk as to implementing or otherwise using the materials is assumed by the implementer and user.
IN NO EVENT WILL THE PARTIES BE LIABLE TO ANY OTHER PARTY FOR LOST PROFITS OR ANY FORM OF INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER FROM ANY CAUSES OF ACTION OF ANY KIND WITH RESPECT TO THIS DELIVERABLE OR ITS GOVERNING AGREEMENT, WHETHER BASED ON BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, AND WHETHER OR NOT THE OTHER MEMBER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

[[authors]]
== Authors

* Birgit Boss, Robert Bosch GmbH
* Daniel Ewert, Robert Bosch GmbH, daniel.ewert@bosch.com
* Sven Erik Jeroschewski, Bosch.IO GmbH
* Lukas Römer, Bosch.IO GmbH, Lukas.roemer@bosch.io
* Michele Santoro
* Andreas Schilling, andreas.schilling3@de.bosch.com
* Georg Schmidt-Dumont, Robert Bosch GmbH, georg.schmidt-dumont@de.bosch.com 
* Andreas Textor, Andreas.Textor@de.bosch.com

[[github]]
== GitHub

https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model

[[participate]]
== Participate

https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/blob/main/CONTRIBUTING.md


This work is provided by the copyright holders under the license MPL-2.0 as defined in https://www.mozilla.org/en-US/MPL/2.0/.
As the separate files in this project are developed independently from each other, copyright notices and alike, are part of those separate files.
